### ISSUE TITLE
Mutually exclusive conditions on deployment with dmcrypt dedicated journal

### ISSUE THREAD

**Issue by 9seconds** [ceph/ceph-ansible#1054]
I've been trying to deploy ceph cluster with dedicated dmcrypted journals and met following:

To prepare OSDs with dmcrypt, i need to set both `raw_multi_journal` and `dmcrypt_dedicated_journal` to `true`: 
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/scenarios/dmcrypt-dedicated-journal.yml#L25-L27

But at the same time, this is invalid settings here: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/checks/check_mandatory_vars.yml#L96

I've tried to remove mutually exclusive `or (dmcrypt_dedicated_journal and raw_multi_journal)` and deployment is OK, but I am not quite sure if it won't break anything else.

**Comment by andrewschoen** [comment]
Thanks for the report. I think the fix here is to remove this line: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/scenarios/dmcrypt-dedicated-journal.yml#L25

The check in ``check_mandatory_vars`` is correct because you really can't use ``dmcrypt_dedicated_journal`` and ``raw_multi_journal`` at the same time.
