### ISSUE TITLE
ansible fails with error message 'dict object' has no attribute u'ansible_eth0'

### ISSUE THREAD

**Issue by tmuthamizhan** [ceph/ceph-ansible#1059]
ansible version: 2.1

error message: 'dict object' has no attribute u'ansible_eth0'

using the latest ceph-ansible upstream repo

extra vars set to pickup upstream ceph build: 
ansible-playbook -v --extra-vars \'{"ceph_dev_branch": "jewel", "ceph_conf_overrides": {"global": {"osd default pool size": 2, "osd pool default pg num": 128, "osd pool default pgp num": 128}}, "ceph_test": true, "ceph_dev_key": "https://download.ceph.com/keys/autobuild.asc", "journal_collocation": true, "ceph_origin": "upstream", "ceph_dev": true, "osd_auto_discovery": true, "journal_size": 1024}\' -i inven.yml site.yml'

inventory:
[clients]
mira027.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'

[mons]
mira027.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'
mira046.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'

[osds]
mira027.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'
mira046.front.sepia.ceph.com monitor_interface='eth0' public_network='172.21.0.0/20'

**Comment by tmuthamizhan** [comment]
looks like its a duplicate of - https://github.com/ceph/ceph-ansible/issues/993

**Comment by leseb** [comment]
@tmuthamizhan if it's a duplicate then please close this.
Does `eth0` exist on your nodes?

**Comment by tmuthamizhan** [comment]
@leseb, yes, am using mira027 and mira046 for my testing and they have eth0 on them.

**Comment by leseb** [comment]
@tmuthamizhan can you show me a `ip -4 a` please? Because usually this error means you're using a wrong interface name.

**Comment by andrewschoen** [comment]
I've been looking into this using another environment created by @vasukulkarni that replicated the problem. I was able to replicate the issue as well with his setup, the interfaces were correct.

I noticed a few things and did get past this issue though:

- In this new environment the ansible version was 1.9.4, I upgraded that to 2.1
- The version of ceph-ansible being used was somewhat stale, I updated that to master@228470a51fdbe7bb97a15560e85d04d44e9a06bd
- The inventory was using two monitors, I reduced that to one so mons could reach quorum.

The specific error seen in this issue was fixed with: https://github.com/ceph/ceph-ansible/pull/1045/commits/0421ade0df6abbafea26e6de31668d37187b5922

However, that commit does not take into account a cluster where monitors are using differing interfaces that are defined in the inventory file. In looking at that template I also can't see how the ``monitor_address`` option still works either as I don't think this bit of code is ever executed: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/templates/ceph.conf.j2#L28-L32

I'll close this for now and open new issues related to ``monitor_address`` usage and a setup where mons have differing interfaces when I have more information on them.

**Comment by leseb** [comment]
@andrewschoen thanks for the detailed analysis.
