### ISSUE TITLE
Update indivudual role repositories

### ISSUE THREAD

**Issue by gaudenz** [ceph/ceph-ansible#1111]
It would be great to have updated individual role repositories which work with ansible 2.2.

I'm not sure how this process works in detail and how often these roles are updated. I've seen the playbook that is apparently used for this. 

To me (but I'm by no means an expert on this) the whole process looks a bit backwards. Wouldn't it be easier to work in the individual roles and to pull them into the ceph-ansible repository? Maybe I'm missing something or doing something wrong, but currently it's a bit a pain to integrate this into an existing ansible setup where you don't want to use the ceph-ansible repository because you already have an inventory and playbooks to setup the base operating system.

**Comment by leseb** [comment]
We currently have this, with the help of #1110 we will be able to push branches and tags to the remote repositories.
The roles are updated manually by me at the moment, which is not ideal. Once we have good with #1110 we will setup a jenkins job to automatically execute the script and push the new changes to the remote repos.

I've found it easier to have everything in one place instead of looking at various repositories. For CI testing it's also easier to have everything in one place so we are testing the whole thing. There are a lot of dependancies between certains roles so it's simpler to keep it that way.

The idea is that shouldn't have to bother to commit to several repos, just leave us the burden of pushing to the remote repos :).

If you don't use ceph-ansible at all and only relies on the galaxy, you can still use a file similar to this:  https://github.com/ceph/ceph-ansible/blob/master/example-ansible-role-requirements.yml which I suppose you already do.

**Comment by gaudenz** [comment]
Oh I did not notice #1110. This looks like a nice way to do it. Automatically updating the role repositories looks like it will get you the best of both worlds. I'll close this issue then as it looks like #1110 will be merged RSN.
