### ISSUE TITLE
Update ceph-ansible to pull packages from chacra?

### ISSUE THREAD

**Issue by batrick** [ceph/ceph-ansible#1137]
After the gitbuilder hiccup yesterday I was looking at changing ceph-ansible to pull from chacra. This code would need updated:

https://github.com/ceph/ceph-ansible/blob/c3cda797383d930745dc4960aaf6dee970f7863d/roles/ceph-common/tasks/installs/redhat_ceph_repository.yml#L32

However, the replacement URL is not trivially changed. Here's an example RPM URL:

    https://3.chacra.ceph.com/r/ceph/wip-multimds-tests/351e8d5a4733b442d36403878fb5b1ba472f778e/centos/7/flavors/default/noarch/ceph-release-1-0.el7.noarch.rpm

This presents two problems:

* The hostname is not static. (i.e. charcra node 3 (?) is part of the hostname and may be different from one build to the next)
* The commit ID for the branch is in the URL. It would be useful if chacra allowed us to ask for the current commit of the branch. Alternatively, we could require that the `ceph_dev_branch` also include the commit ID but that's not really acceptable IMO.

**Comment by batrick** [comment]
@alfredodeza what do you think?

**Comment by andrewschoen** [comment]
@batrick Agreed that this needs to happen. I was thinking we'd use these urls instead of ceph-release. 

https://3.chacra.ceph.com/repos/ceph/wip-multimds-tests/351e8d5a4733b442d36403878fb5b1ba472f778e/centos/7/flavors/default/repo/

Ubuntu doesn't have an equivalent to ceph-release, but chacra has the same endpoint for the ubuntu repos.

In regards to your first problem, we've been discussing implementing a feature in shaman that would remove that. It'd be nice to have a url like: https://shaman.ceph.com/repos/ceph/wip-multimds-tests/351e8d5a4733b442d36403878fb5b1ba472f778e/default/7188/repo/ that would redirect you to the appropriate chacra instance. The shaman ID of 7188 is an issue there, but we can probably get around that.

**Comment by alfredodeza** [comment]
No solutions yet to this, but wanted to add that none of these systems understand what "latest sha1" is like git does. These systems do understand what the "last build for a branch" is, and that might be enough for us to provide something that will be good enough.

I would dislike (from a user perspective) having to know what sha1 do I need to install, but it is useful to optionally provide it.

Piggy-backing from @andrewschoen 's idea, would be to make shaman provide the repository but using queryargs to support all the variables that may be needed (like distro and distro version) while allowing the optional ones like sha1

**Comment by alfredodeza** [comment]
Fixed with PR #1169
