### ISSUE TITLE
timeouts are needed for possible hangs

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#1161]
There are some tasks that will hit parts of Ceph that will wait for ever:

    TASK [ceph-mon : collect admin and bootstrap keys] *****************************
    task path: /home/jenkins-build/build/workspace/ceph-ansible-prs-ansible2.2-centos7_cluster/roles/ceph-mon/tasks/start_monitor.yml:64

This is stuck because it hits an issue where the bootstrapping process will try forever until it can get the keys.

A fix is now in the newest Jewel but ceph-ansible needs to support everything that doesn't have this changeset: https://github.com/ceph/ceph/pull/11749

See issue #760 

There are numerous reasons to *why* it might wait/loop forever, so the right fix here is to properly timeout on tasks that request these keys with ceph-create-keys

**Comment by leseb** [comment]
As far as I remember this was a safety measure in some old releases. I'm not sure if we still need this as `ceph-create-keys` should get fired when the monitor process starts.  I remember having issues on centos 7.0 and 7.1 not triggering `ceph-create-keys`.
It's also a safe guard in case the mon process doesn't start properly. However we have this task right after "wait for client.admin key exists" that would fail after 300 seconds.

I just tried to remove the "collect admin and bootstrap keys" task and it seems to be working perfectly on 3 mons. I suspect we can remove this task.

**Comment by andrelohmann** [comment]
Hi there, I know this issue is quite old, but I'm having exactly this problem again on ceph-ansible stable-3.1 deploying the monitor on an ubuntu 16.04.

root@mon1:~# ceph-create-keys --cluster ceph -i mon1 -t 30
INFO:ceph-create-keys:Talking to monitor...
Cluster connection interrupted or timed out
Cluster connection interrupted or timed out
INFO:ceph-create-keys:Cannot get or create admin key, permission denied

**Comment by leseb** [comment]
@andrelohmann please look at your monitor logs to see what's going on.
