### ISSUE TITLE
waiting for clean pgs run sooner before conf is updated on ceph

### ISSUE THREAD

**Issue by vasukulkarni** [ceph/ceph-ansible#1271]
I see 2 issues

1) the retries are 80 instead of 40( there are 2 retries printed for same number)
2) also looks like the task is run way sooner than in the end

https://paste.fedoraproject.org/542578/97868914/raw/

Since it is based on user config, it should be good to provide option even all pgs are not in active state.

Full logs:
http://magna002.ceph.redhat.com/vasu-2017-02-01_13:54:15-smoke-jewel---basic-multi/263374/teuthology.log

**Comment by andrewschoen** [comment]
@vasukulkarni Do you have two osd nodes? I imagine it's running that check on both nodes, which is why you see the duplication.

The handlers run at the end of each play in a playbook. You'll see handlers fire after each daemon is installed/configured, ``site.yml.sample`` separates each daemon type into it's own play.  This is why you see the osd handlers fire in the middle of your ansible run.

Are you asking for an option to skip the pg check? The title of this issue I don't think is correct because it's the ceph.conf creation that actually triggers the handlers, https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/generate_ceph_conf.yml#L20-L25

**Comment by vasukulkarni** [comment]
Sorry my bad, yes it is correct, its triggered at the end,

Also the other thing i am asking is for it to skip this check when running intentionally with lower config settings, probably i should raise a different tracker for that?

**Comment by andrewschoen** [comment]
Yeah, I think it'd be best to close this one and open another for that. Thanks!

**Comment by vasukulkarni** [comment]
sure, thanks.
