### ISSUE TITLE
Installation fails on Debian due to ceph-fs-common package

### ISSUE THREAD

**Issue by BastiPaeltz** [ceph/ceph-ansible#1481]
I ran the playbook on `Debian Jessie` with the settings:

```
ceph_origin: upstream
ceph_stable: true
```

This fails with the error message described in [https://github.com/ceph/ceph-ansible/issues/1387](https://github.com/ceph/ceph-ansible/issues/1387). Apparently `ceph-fs-common` has merged in Kraken so the installation fails. 

After removing [this](https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L75) line, the installation succeedes.

**Comment by andrewschoen** [comment]
I've been trying to get around this issue as well. @ktdreyer do you have any ideas here?

I've noticed that when we install upstream ceph for debian we do not install the daemon specific packages, we just install this list on most all the nodes: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L72

The quick fix would be to remove ``ceph-fs-common`` from ``debian_ceph_packages`` and only install it when we're installing jewel. I'd really like to avoid version specific installs if possible though. Would installing the daemon specific packages help? How do we address the concern about upgrading mentioned in ``ceph-common/defaults/main.yml`` for ``debian_ceph_packages``? Is it still a concern at all?

**Comment by ktdreyer** [comment]
Looking at that comment, I think this may have been a workaround for the Debian packaging bug(s) where certain sub-packages were never upgraded alongside everything else.

That should be fixed as of https://github.com/ceph/ceph/pull/7931 (aka Jewel).

Since we've dropped pre-Jewel support here in ceph-ansible, I think we can drop this workaround too. That would mean only listing the `ceph` package for `debian_ceph_packages` there.

(And yeah, per-daemon packages would be great to unify the Ansible code for upstream and downstream, but that could be a separate change.)

**Comment by andrewschoen** [comment]
Ok, I'll make a PR to remove ``debian_ceph_packages`` and just install ``ceph`` here: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/installs/install_on_debian.yml#L20

We can tackle the per-daemon packages later.
