### ISSUE TITLE
ceph-disk: support osd new to replace a failed OSD

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#1602]
New infrastructure playbook?
See: https://github.com/ceph/ceph/pull/15432

**Comment by MatthewVernon** [comment]
This would be nice, but tricky, I suspect - we hot-swap the disks on our OSD boxes, and currently I have a "look in kern.log to see what disk just got added; ceph-disk prepare... that" step, which seems difficult to ansible-ise.
Also, if people are using e.g. NVME partitions for journal devices, you want to re-use the now-not-needed partition from the dead OSD rather than trying to make another partition.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
