### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#1610]
Once the testing harness was documented, a full documentation layout and workflow was put into place to publish docs to docs.ceph.com/ceph-ansible

The current non-test docs are scattered in README files in each role. Some of those explain some functionality but they can't fit everything in one single file anymore.

There are several problems with the current documentation:

* Has no mention of "getting started" or "guides"
* Explains the "what" but not "how". For example it documents what features are supported (like cephx) but not how to interact with it, enable it, configure it, or how it will look when working
* single README file(s) no longer fits the size of the project

**Comment by bengland2** [comment]
+1   Specifically we need more of a user's guide - what are the minimum set of variables that the user must define in order to get a working Ceph cluster, and how to define them.   Network config is partially covered in top-level README.md, but not OSD scenarios and when and how to use them.  I suggest putting info on how to run and test in Vagrant in a separate .md for developers.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
