### ISSUE TITLE
Osd's won't start after reboot

### ISSUE THREAD

**Issue by alonbl92456** [ceph/ceph-ansible#1643]
Hey,
i'm using the latest version of ceph-ansible to deploy ceph jewel.
After server reboot the osds on the server won't come up.
i can start the manually with ceph-disk activate all.
is there any way to solve this ? or just add ceph-disk activate all to rc.local in each osd server ?

thank u for your help!

**Comment by alfredodeza** [comment]
This is a well known behavior when using ceph-disk which relies on udev triggers. Here is a recent bugzilla issue: https://bugzilla.redhat.com/show_bug.cgi?id=1439210

Unfortunately, most of these issues are very hard to debug and track down because of how udev works. I think adding the entries to rc.local would be a fine workaround, I would also make sure that if going down that route, you disable the Ceph udev rules to prevent race conditions when activating
