### ISSUE TITLE
ceph-ansible broken: Error initializing cluster client

### ISSUE THREAD

**Issue by tmuthamizhan** [ceph/ceph-ansible#1712]
looks like ceph-ansible is broken and failing with error "Error initializing cluster client: Error('error calling conf_read_file: error code 22',)"

latest logs: http://pulpito.front.sepia.ceph.com/teuthology-2017-07-25_05:15:47-ceph-ansible-kraken-distro-basic-vps/

**Comment by leseb** [comment]
The problem is that you used ceph_dev on a kraken branch, then because of this https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/release.yml#L2-L4 ceph_release was set to kraken because the current default of ceph_stable_release is kraken. However, because of ceph_dev this https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/release.yml#L6-L12 overrode ceph_release.
Fix here: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/release.yml#L6-L12

From now on please, always set on which Ceph release you are working on, even with ceph_dev.

**Comment by vasukulkarni** [comment]
I am reopening to get different solution to this, It is hard to handle this in teuthology, since a ceph_dev_branch can point to something like "wip-testing-2" , at that stage without installing its not possible to detect what is ceph_stable_release, since ceph-ansible handles the install its knows wheter its 10.x, 11.x or 12.x for various release flag.

**Comment by andrewschoen** [comment]
@vasukulkarni I disagree, I think making ``ceph_stable_release`` mandatory is a workable solution. The problem is that we sometimes need to make decisions in ceph-ansible before install for differing versions of ceph, this is why it's nice to know what version you're expecting to install before we actually install the packages.

I recently was testing the ``wip-volume`` branch of ceph and I knew it was based of luminous so I just set ``ceph_stable_release: luminous`` as well. Why couldn't teuthology or the user initiating the teuthology test do the same?

**Comment by vasukulkarni** [comment]
@andrewschoen Its just not only me running the tests, there could be other users who are not aware what to set in overrides when running tests, since many things are handled inside the task.  Something thats gets set automatically inside ceph-ansible is a good solution. Is it not possible to handle this in ceph-ansible now?

**Comment by tmuthamizhan** [comment]
@vasukulkarni, we can very well set it along with ceph_dev_branch in
ceph-ansible task.

**Comment by leseb** [comment]
+1 @tmuthamizhan, if you have  `ceph_dev_branch` already, then you kinda know which ceph version is built underneath. If you know a reliable way of getting the ceph version from a  `ceph_dev_branch` then we might be able to automate that. If not that you'll have to set `ceph_stable_release` accordingly.

**Comment by leseb** [comment]
I have a solution here:
