### ISSUE TITLE
Automated Jenkins testing broken

### ISSUE THREAD

**Issue by fghaas** [ceph/ceph-ansible#1927]
This is a bit of a meta-issue, but I noticed it sending PRs over the last few days and it's rather annoyingly persistent: the Jenkins tests seem to be broken to the point of uselessness, which is probably a barrier to entry for new and occasional contributors.

**Comment by leseb** [comment]
This comment suits so well Florian, always complaining and never thankful to the project.
To be honest, I don't like the way you talk, always cold and the impression everything is granted.

I value your technical skills but I can't so much about your social skills.
I think you should revisit the way you engage conversation; your writing lacks manner.
Otherwise, you won't gain much attention if you continue on that path.

I hope I'm mistaking, and that this is only a language issue.
Anyway, I hope things will change and that we can continue to collaborate in a more friendly manner.

Now, regarding the issue, yes we've noticed (we work on this project on a daily basis).
This is as frustrating for us as it is for you (to not say even more). We are currently addressing the issues.

**Comment by fghaas** [comment]
Neither offense, nor complaint intended, and thanks for pointing out the wording. Let me clarify.

Here's the motivation for filing this: whenever I send a contribution (here or anywhere else), I always make a point of making sure that it's not breaking anything. That's what the integration tests are for, I assume, and it's good that they exist. In a bunch of projects it's also safe to assume that PRs don't ever get reviewed as long as they break the CI test suite. So, rather than attaching a comment to each of my PRs saying "I really *think* that the Jenkins run breakage *isn't* due to my patch, but I'm not 100% sure so please let me know if it is and I'll fix it", I thought I'd throw in this issue here. That way, interested parties (including myself) could watch the issue, and once it is marked fixed, we'd all understand that yes, breaking tests *is* a blocker. Right now that is not clear. If you prefer to handle this a different way, then please feel free to close this issue.

**Comment by leseb** [comment]
I understand the concern, and I've been feeling the pain for weeks. We are currently in the process of fixing some of the major bugs in the CI, as well as introducing handy features too.

Reported issues:

- [ ] `uninitialized constant VagrantPlugins::ProviderLibvirt::Action::ShareFolders`

- [ ] `java.io.EOFException`

Errors are currently being investigated, this is mainly due to a resource issue. We quite often reach our quota limit on the cloud provider with boot jenkins slave...

So far this is what we came up with in terms of features:

- [ ] `ability to not run the CI on a particular PR (with commit message 'do not test')`, this now possible by adding the tag `[skip ci]` in the title of the PR.

- [ ] `ability to do a "only run" selected scenario`, possible with the feature above, you can add the `[skip ci]` tag in the title, then remove it and call the specific scenario you want with `jenkins test <scenario name>`.

- [ ] `Annoying to 'jenkins test ... ' all the time, need a 'jenkins restest failures'`

The later, ideally should disappear naturally once the CI errors have been fixed.

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
