### ISSUE TITLE
`ceph-ansible` suite in upstream point release validation process.

### ISSUE THREAD

**Issue by yuriw** [ceph/ceph-ansible#1938]
Awhile ago we included `ceph-ansible` suite to be part of any point release validation process.
Which means that during such validations `ceph-ansible` suite expected to pass.

For example for jewel v10.2.8 `ceph-ansible` suite passed as expected http://tracker.ceph.com/issues/19538#note-89
 
However, if you look at nighties runs now, this suite http://pulpito.ceph.com/?suite=ceph-ansible it's solidly red.

It raised several questions:

1.  Do we want to keep running this suite as part of nighties and point releases validations?
2.  Who is "babysitting"  `ceph-ansible` suite on ongoing basis?  See ref: http://tracker.ceph.com/projects/ceph-releases/wiki/HOWTO_monitor_the_automated_tests_AKA_nightlies
3.  If the answer to question 1 is _YES_ , how do we make sure that `ceph-ansible` is using either `stable` or `backwards compatible` versions of `ansible` so tests don't fail due to environmental issues?
4.  If the answer to question 1 is _NO_, what alternative process do we use to validated `ceph-ansible` for releases if any?

**Comment by vasukulkarni** [comment]
@yuriw 

for 1.) Yes we have to keep running this, the reason we had so many issues was fast moving changes in ceph-ansible and trying to keep it up for master branch and then eventually we have to backport all those to luminous + jewel. 
 for jewel atleast we can try to fix the ceph-ansible branch to stable since we dont expect to carry over many of those master changes and the current test exists in jewel branch should be sufficient.

for 2.) we have had green runs in master for some time but I guess the purge cluster issue for which the PR exists is causing the tests to fail(https://github.com/ceph/teuthology/pull/1112),  For backports I am not really sure, probably you can take cherrypick those commits or add some more labels to make sure the backport team notices them.

3) Both @andrewschoen and I agree we have to use latest 'master' branch for testing luminous/master of ceph,  we can use stable branch for 'jewel'

**Comment by yuriw** [comment]
One of the issues we need to agree on - how do we backport ceph-ansible related PRs fro example for jewel v10.2.10

What do you think @vasukulkarni @smithfarm @theanalyst  @andrewschoen ?

**Comment by guits** [comment]
Closed due to inactivity, feel free to re-open if needed. Thanks!
