### ISSUE TITLE
cephx permission problems

### ISSUE THREAD

**Issue by tstrul1** [ceph/ceph-ansible#2296]
according to this:
http://lists.ceph.com/pipermail/ceph-users-ceph.com/2017-November/022695.html
and the luminous upgrade instructions, any ceph client with [mon] read-only need to have:
"osd blacklist" cap as well.
http://docs.ceph.com/docs/master/release-notes/#upgrade-from-jewel-or-kraken (section 6)

currently when using ceph-ansible. cinder clients get only read access on mons and when compute crushes we get a stale lock

**Comment by leseb** [comment]
This is indeed concerning. We need to look into this ASAP.

**Comment by guits** [comment]
@leseb should we consider all keyrings with [mon] read-only need to have the `osd blacklist` capability or only `client.cinder` ?

**Comment by leseb** [comment]
@guits basically all the client keys, so cinder etc, all OpenStack keys.

**Comment by guits** [comment]
@leseb ok, good. Will send a PR for this

**Comment by leseb** [comment]
@guits cimer maggle

**Comment by tstrul1** [comment]
any update on this?

**Comment by E46-S54** [comment]
Also keen to see this implemented as I've seen VMs fail to boot after a hypervisor failure.

Thanks

**Comment by ionutbiru** [comment]
the commit cherry picked into stable-3.2 caused a problem with openstack services.
now all the keys are not able to do any actions from cinder/glance/etc due to authorization error.
cinder doesn't create any volumes because it never timeouts,rados_connect_timeout is -1

how is the right approach to fix services in openstack?

# rbd create --size 1 --user cinder vms/test
2019-08-21 10:42:31.640 7ff88c434700  0 -- 172.29.100.200:0/872473912 >> 172.29.100.200:6822/1328282 conn(0x5567fb56d6b0 :-1 s=STATE_CONNECTING_WAIT_CONNECT_REPLY_AUTH pgs=0 cs=0 l=1).handle_connect_reply connect got BADAUTHORIZER

**Comment by ionutbiru** [comment]
https://docs.ceph.com/docs/master/releases/luminous/#upgrade-from-jewel-or-kraken

the osd blacklist should be under mon not under osd. the tests keys seems correct, only the openstack keys are incorrect.
