### ISSUE TITLE
var's qurstion

### ISSUE THREAD

**Issue by sharonog101** [ceph/ceph-ansible#2720]
Hi All , 
can someone explain how ansible build his vars : mons & fetch_directory & mon_group_name

**Comment by leseb** [comment]
What are you looking for exactly? What do you want to know?

**Comment by sharonog101** [comment]
hi , i want to know hot ceph ansible in openstack deploymnet build the hosts in the site-docker.yml.sample ... 

- hosts:
  - mons
  - agents

{ no such names in the etc/ansibe/hosts ... } 
as they run in serial i must control the order of the run .

**Comment by leseb** [comment]
Sorry, your request is still unclear. Please elaborate a bit more.
Thanks.

**Comment by sharonog101** [comment]
1 - ok ... cbis-ansible deploy the following file : site-docker.yml.sample as you probably know . 
     this file also have definition of hosts to run on different roles ....  
     my question is how the hosts section get  build ? ( /etc/ansible/hosts not includes those names )

**Comment by guits** [comment]
@sharonog101 
If you are using Vagrant with the Vagrantfile provided in this playbook, the inventory is dynamically generated [here](https://github.com/ceph/ceph-ansible/blob/master/Vagrantfile#L52-L62).
Otherwise, it's up to you to generate the inventory depending on your infra. The definitions of hosts you see in your site-docker.yml must match the host section you have in your inventory host file.

I assume what you saw in your /etc/ansible/hosts is the content of default file provided by the packaging.

**Comment by guits** [comment]
I think there is no actual issue here, let's close this. Feel free to re-open if needed.
