### ISSUE TITLE
ceph-config: actions: config_template: module fails if diff is enabled

### ISSUE THREAD

**Issue by k0ste** [ceph/ceph-ansible#2742]
Reproducer:
 * Ansible 2.4.3
 * ansible.cfg:
```
[diff]
always = yes
context = 3
```

I think this is because source is already moved to `/etc/ceph/ceph.conf`.

```python
TASK [ceph-config : generate ceph configuration file: ceph.conf] *************************************************************************************
task path: /home/k0ste/ceph-ansible/roles/ceph-config/tasks/main.yml:12
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 130, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/k0ste/ceph-ansible/plugins/actions/_v2_config_template.py", line 660, in run
    transferred_data, task_vars))
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 945, in _get_diff_data
    st = os.stat(source)
OSError: [Errno 2] No such file or directory: '/tmp/ansible-tmp-1528478088.05-186932576205581/source'

fatal: [ceph-osd3.opentech.local]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

**Comment by guits** [comment]
@andymcc do you think a fix could be applied in openstack-ansible-plugins then we resync the file in ceph-ansible?

**Comment by andymcc** [comment]
Definitely, let me play around with --diff mode some to check its working, although for ceph-ansible it doesn't usually work that well since a bunch of important tasks are not run and so it can't generate the file. Unless you run the config tasks separately. 

https://github.com/openstack/ansible-config_template would be the place to sync from - i'll test the current module in ceph-ansible vs the ansible-config_template one and see.

Did you have steps to recreate the issue @k0tse ? Or was it just a regular run with --diff.

**Comment by andymcc** [comment]
sorry for the delay - i have a fix up, once that merges we should sync: https://review.openstack.org/576091

I'll push for a merge on that PR - and then post a PR for this.

**Comment by andymcc** [comment]
a bit more detail, --diff will work with --check as it is now, but the bug prevents it from working without --check mode.

**Comment by andymcc** [comment]
Pr is up! Should fix this issue.
