### ISSUE TITLE
run a dummy container (sleep 300) from where we can create pool(s)/key(s)

### ISSUE THREAD

**Issue by GregMeno** [ceph/ceph-ansible#2762]
Is sleep 300 really the best approach here?

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-client/tasks/create_users_keys.yml#L15-L28

this seems to be brittle and surprising.

**Comment by leseb** [comment]
We know it's not ideal, although the key creation shouldn't take more than 300 sec if it does you have certainly 1000 keys or something, which doesn't seem realistic at this point.

**Comment by guits** [comment]
At first glance it could be seen as something not really nice, indeed.
As @leseb said, it would be surprising if this action took more than 300sec.
I think the real issue here is that perhaps it needs a new approach for this use case, but I'm not sure this is something we want to do right now since it has just got 'stabilized' with v3.1.0rc9. By the way, I think we are going to have much more items/tasks with higher priority to address very soon.

**Comment by guits** [comment]
Let's close this now, I think we should discuss this when we will be refactoring this role.
