### ISSUE TITLE
Invoking purge-cluster.yml should destroy any LVM setups created by the deploy process

### ISSUE THREAD

**Issue by zmc** [ceph/ceph-ansible#3156]
**Bug Report**

What happened:
Deployed a cluster, purged, attempted to re-deploy.

What you expected to happen:
Deploy failed with "RuntimeError: Unable to use device, already a member of LVM: /dev/sdb""

Share your group_vars files, inventory
The only relevant bit should be:
```
osd_scenario: lvm
devices:
  - /dev/sdb
  - /dev/sdc
  - /dev/sdd
```

**Environment**:
* OS (e.g. from /etc/os-release): RHEL 7.4
* Kernel (e.g. `uname -a`): 3.10.0-693.21.1.el7.x86_64
* Ansible version (e.g. `ansible-playbook --version`): 2.6.4
* ceph-ansible version (e.g. `git head or tag or stable branch`): master
* Ceph version (e.g. `ceph -v`): 14.0.0-3366-g8cb9e3e

**Comment by andrewschoen** [comment]
I think this is because ``ceph-volume lvm zap`` is run against devices and lvs defined in ``lvm_volumes`` but ``purge-cluster.yml`` does not support zapping raw devices found in ``devices`` if the ``osd_scenario`` is ``lvm``.

https://github.com/ceph/ceph-ansible/blob/master/infrastructure-playbooks/purge-cluster.yml#L353
