### ISSUE TITLE
python bindings (libselinux-python) aren't installed : Even though libselinux is installed and selinux is disabled

### ISSUE THREAD

**Issue by Darknight123** [ceph/ceph-ansible#3634]
**Bug Report**

What happened: We are trying to onboard one of the linux server into ansible 2.6.3. This server has selinux disabled in /etc/selinux/config , libselinux is already installed and we are asking ansible to use python26 path (ansible_python_interpreter=/usr/bin/python2.6). But still while connecting to ansible server this remote machine throws error as Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!. Please provide a fix to this
Remote server is using Python 2.6.8 and libselinux package install version is libselinux-python-1.33.4-5.7.el5

What you expected to happen:ideally if selinux is disabled ansible should not check libselinx and even if it is checking and if its already installed on remote machine it should detect it.

How to reproduce it (minimal and precise):

Share your group_vars files, inventory
[ttylinux]
xx.xx.xx.xx.xxx
[ttylinux:vars]
ansible_python_interpreter=/usr/bin/python2.6
**Environment**:
* OS (e.g. from /etc/os-release): ansible server - 7.3 , remote server - 5.7 
* Kernel (e.g. `uname -a`): remote server - 2.6.18-274.el5 , ansible server - 3.10.0-514.el7.x86_64
* Docker version if applicable (e.g. `docker version`): Not used
* Ansible version (e.g. `ansible-playbook --version`):2.6.3
* ceph-ansible version (e.g. `git head or tag or stable branch`):not used
* Ceph version (e.g. `ceph -v`):not used

**Comment by dsavineau** [comment]
@Darknight123 this issue needs to be open on ansible project because it's not related at all with ceph-ansible project.

Also I saw something similar when using ansible via a python virtualenv because selinux python bindings can't be install in the venv, only via rpm package.

https://github.com/ansible/ansible/blob/stable-2.6/lib/ansible/module_utils/basic.py#L1056-L1067
https://dmsimard.com/2016/01/08/selinux-python-virtualenv-chroot-and-ansible-dont-play-nice/
