### ISSUE TITLE
rolling_upgrade.yml fails after checking "clean pgs" with cluster flags still set

### ISSUE THREAD

**Issue by peanuts250** [ceph/ceph-ansible#3961]
**Bug Report**

What happened:
branch 3.2, rolling_upgrade.yml sets flags nout and norebalance, which is fine, however, after upgrading one osd it checks for clean pgs and fails. PGs are not going to be clean with the flags still set. Especially if any I/O occurred to the PG when the OSD was upgraded and restarted

What you expected to happen:
clean pg check should **ONLY** occur when all flags have been unset to ensure the cluster recovers 

How to reproduce it (minimal and precise):
Setup a cluster (version mimic) with multiple OSD hosts, create rbd pool, create an image, start a FIO job that loops and writes to the image. Configure ceph-ansible branch 3.2 group_vars/all.yml repo to be "nautilus", execute rolling_upgrade.yml ansible against the cluster hosts. When the first OSD host upgrades, it will attempt to look for "clean pgs" and fail because some PG will be in the state `active+undersized+remapped+backfilling` and the flag norebalance is still set preventing it from backfilling

**This issue is also seen when going from luminous -> mimic** using ceph-ansible 3.2

Share your group_vars files, inventory
**Inventory**
[inventory.txt](https://github.com/ceph/ceph-ansible/files/3167007/inventory.txt)

**group_vars/all.yml**
[all.txt](https://github.com/ceph/ceph-ansible/files/3167013/all.txt)

**group_vars/osds.yml**
[osds.txt](https://github.com/ceph/ceph-ansible/files/3167014/osds.txt)

**Environment**:
VMs running Ubuntu 18.04

* OS (e.g. from /etc/os-release):
Ubuntu 18.04

* Kernel (e.g. `uname -a`):
Linux hostadmin 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Docker version if applicable (e.g. `docker version`):
N/A

* Ansible version (e.g. `ansible-playbook --version`):
ansible-playbook 2.6.16
  config file = /home/vagrant/ceph-ansible-3.2/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]

* ceph-ansible version (e.g. `git head or tag or stable branch`):
stable-3.2

* Ceph version (e.g. `ceph -v`):
before upgrade:  13.2.5
after upgrade: 14.2.1

**Comment by dsavineau** [comment]
stable-3.2 doesn't support nautilus.
if you want to upgade from mimic to nautilus then you need to use the stable-4.0.

In other words:

- initial mimic deployment with stable-3.2
- upgrade to nautilus with stable-4.0

**Comment by peanuts250** [comment]
That is true, however, stable-4.0 is still in rc phase. When I run rolling_update from 4.0rc I get a ton of errors, asking for variables to be set which is never the case with a final release

Looking at a diff between 4.0 and 3.2 rollingupdate, I see no logic difference in how the flags are handled. If not mistaken it still has the flags set when checking for "clean pgs", which should not be the case

**Comment by dsavineau** [comment]
I just tested this manually on a nautilus cluster with IO activity during osd stop/start and I never had remapped or backfilling pgs. Only undersized and degraded pgs that recovered correctly.

```console
# ceph -s -f json | jq .health.checks.OSDMAP_FLAGS.summary.message
"noout,norebalance flag(s) set"
# ceph -s -f json | jq .pgmap.pgs_by_state
[
  {
    "state_name": "active+clean",
    "count": 288
  }
]
```

Running some IO operations on that cluster and then stop an OSD.
```console
# ceph -s -f json | jq .pgmap.pgs_by_state
[
  {
    "state_name": "active+clean",
    "count": 144
  },
  {
    "state_name": "active+undersized",
    "count": 125
  },
  {
    "state_name": "active+undersized+degraded",
    "count": 19
  }
]
```

Restarting the OSD and the pgs recovered slowly

```console
# ceph -s -f json | jq .pgmap.pgs_by_state
[
  {
    "state_name": "active+clean",
    "count": 243
  },
  {
    "state_name": "active+recovery_wait+degraded",
    "count": 30
  },
  {
    "state_name": "activating",
    "count": 12
  },
  {
    "state_name": "activating+degraded",
    "count": 2
  },
  {
    "state_name": "active+recovering+degraded",
    "count": 1
  }
]
# ceph -s -f json | jq .pgmap.pgs_by_state
[
  {
    "state_name": "active+clean",
    "count": 255
  },
  {
    "state_name": "active+recovery_wait+degraded",
    "count": 32
  },
  {
    "state_name": "active+recovering+degraded",
    "count": 1
  }
]
# ceph -s -f json | jq .pgmap.pgs_by_state
[
  {
    "state_name": "active+clean",
    "count": 288
  }
]
```

**Comment by peanuts250** [comment]
I don't think that means it can *never* happen. I was able to reproduce twice

**Comment by dsavineau** [comment]
I'll try with fio but I need to deploy a mimic cluster because fio doesn't seem to support msgr v2 config with nautilus.

**Comment by peanuts250** [comment]
Confirmed 3rd time, this time I went from luminous to mimic. I have 2 PG stuck (out of 100)
`2  active+undersized+remapped+backfilling`

ceph-ansible 3.2 -> TASK [waiting for clean pgs...]  -> FAILED

```root@hostadmin:~/ceph-ansible# ceph pg dump_stuck
ok
PG_STAT STATE                                  UP      UP_PRIMARY ACTING ACTING_PRIMARY
1.43    active+undersized+remapped+backfilling [6,5,4]          6  [4,5]              4
1.37    active+undersized+remapped+backfilling [3,1,8]          3  [3,8]              3
```

As I mentioned in my previous message, it doesn't _always_ happen, for instance, of the three OSD hosts, hostosd1 had no issues upgrading, hostosd2 did. 

I think it's a really bad idea to check for pg clean with flags set....

**Comment by guits** [comment]
reproduced this behavior on a mimic cluster.

however, not checking PGs state after an host has been upgraded could be dangerous, checking it after flags are unset would be a bad idea as well I think since it means we wouldn't check anything until all OSDs have been upgraded. We should probably rethink that check instead.

I first thought we could add norecover+nobackfill flags and modify that check to allow more combinations like :
- `active+clean`
- `active+clean+scrubbing`
- `active+undersized+degraded+remapped+backfill_wait` 
- `active+undersized+degraded+remapped+recovery_wait`

the thing is, even with flags `norecover+nobackfill` set, I could get PGs stuck in `active+undersized+degraded+remapped+backfilling` and/or `active+recovering+undersized+degraded+remapped` states (which is quite surprising at first glance) until flags `norecover+nobackfill` are unset.

By the way, I'm unsure we would be covering all acceptable PGs state combinations with this approach.

**Comment by peanuts250** [comment]
@guits I don't see why it would be "bad" after each OSD upgrade, unset the flags, then enter the check clean pgs loop (pgs will recover and become clean during this time), THEN set the flags back, upgrade next OSD. It's simple and gets the intended result. The only downside to this is you will have migration/recovery with mismatched OSD versions but this should not be an issue.

**Comment by guits** [comment]
> The only downside to this is you will have migration/recovery with mismatched OSD versions but this should not be an issue.

This is a concern I had but I don't mind giving this a try, in any case I think it is worth it.

**Comment by peanuts250** [comment]
@guits the serial nature of upgrade implies that ceph must be mismatched at some point regardless of this issue

**Comment by guits** [comment]
see https://github.com/ceph/ceph-ansible/commit/0205f6d6456cf9c4c8bf4ca79c009542146c10cc

**Comment by skjoedt** [comment]
@guits this may still be a problem in Nautilus. 

We're running ceph-ansible stable-4, version:

```
$ git rev-parse --verify HEAD
c0c90c67477fecf8dd87c80bb4c15e89819c18a6
```

We were updating a system from 14.2.5 to 14.2.19 using the `ceph-ansible/infrastructure-playbooks/rolling_update.yml` playbook. 

After upgrading the first node, it wasn't able to wait for pgs to clean. The status of the cluster showed several pgs in backfilling mode. 

```
  cluster:
    id:     c4db7a8e-e5da-48ec-9efc-7ccf3f9818ab
    health: HEALTH_ERR
            noout,nodeep-scrub flag(s) set
            Module 'pg_autoscaler' has failed: Module not found

  services:
    mon: 3 daemons, quorum atlantis-1,atlantis-2,atlantis-3 (age 20h)
    mgr: atlantis-mgr(active, since 20h)
    mds: cephfs:1 {0=atlantis-1=up:active} 1 up:standby
    osd: 15 osds: 15 up (since 20h), 15 in (since 9w); 16 remapped pgs
         flags noout,nodeep-scrub

  data:
    pools:   5 pools, 401 pgs
    objects: 29.37M objects, 30 TiB
    usage:   50 TiB used, 43 TiB / 94 TiB avail
    pgs:     4524887/88114437 objects misplaced (5.135%)
             385 active+clean
             15  active+remapped+backfill_wait
             1   active+remapped+backfilling

  io:
    client:   255 B/s rd, 8.0 KiB/s wr, 0 op/s rd, 2 op/s wr
    recovery: 10 MiB/s, 8 objects/s
```

Notice the flags (noout,nodeep-scrub) are different from the original post. 

## pgs are backfilling

We saw an odd number of objects (5.135%) marked as misplaced. As far as I can see from other comments this is unexpected. What's more is that these objects doesn't seem to decrease.

We increased the recovery priority in an attempt to speed up the backfilling:

```
$ ceph config dump
WHO   MASK LEVEL    OPTION                                 VALUE                     RO 
  osd      advanced osd_client_op_priority                 3                            
  osd      advanced osd_max_backfills                      12                           
  osd      advanced osd_recovery_max_active                12                           
  osd      advanced osd_recovery_op_priority               63                           
```

And after 5 days of idle client use we are at 6.042% misplaced objects:

```
  cluster:
    id:     c4db7a8e-e5da-48ec-9efc-7ccf3f9818ab
    health: HEALTH_ERR
            noout,nodeep-scrub flag(s) set
            Module 'pg_autoscaler' has failed: Module not found
            16 pgs not deep-scrubbed in time
 
  services:
    mon: 3 daemons, quorum atlantis-1,atlantis-2,atlantis-3 (age 4d)
    mgr: atlantis-mgr(active, since 4d)
    mds: cephfs:1 {0=atlantis-1=up:active} 1 up:standby
    osd: 15 osds: 15 up (since 4d), 15 in (since 10w); 32 remapped pgs
         flags noout,nodeep-scrub
 
  data:
    pools:   5 pools, 401 pgs
    objects: 29.37M objects, 30 TiB
    usage:   53 TiB used, 41 TiB / 94 TiB avail
    pgs:     5323498/88115226 objects misplaced (6.042%)
             369 active+clean
             25  active+remapped+backfilling
             7   active+remapped+backfill_wait
 
  io:
    client:   170 B/s rd, 681 B/s wr, 0 op/s rd, 0 op/s wr
    recovery: 163 MiB/s, 147 objects/s
```

## Regarding `Module 'pg_autoscaler' has failed: Module not found`

*It deserves a mention here, as I am not sure what implications it has on the update.*

We recently installed a new manager node using `site.yml`. For unknown reasons, the ceph installation here were Octopus, even though our inventory was:

```yaml
ceph_origin: repository
ceph_repository: community
ceph_mirror: http://eu.ceph.com
ceph_stable_release: nautilus
```

We speculate that because this node was running Ubuntu 20.04 which contains the official ceph repository with Octopus, this repository was prioritized over the apt repository configured by ceph-ansible.

I'm not sure if this is related to the problem above.
