### ISSUE TITLE
No package matching 'rhscon-agent' found available, installed or updated

### ISSUE THREAD

**Issue by JinsYin** [ceph/ceph-ansible#4020]
**Environment**:
* OS: CentOS 7.5
* Kernel: 3.10.0-693.el7.x86_64
* Ansible version: 2.6.9
* ceph-ansible version: stable-3.2
* Ceph version: 13.2.5

**Issue**:

```txt
fatal: [192.168.1.x]: FAILED! => {"changed": false, "msg": "No package matching 'rhscon-agent' found available, installed or updated", "rc": 126, "results": ["No package matching 'rhscon-agent' found available, installed or updated"]}
```

**Question**:

What is `ceph-agent` and what is its relationship with salt and redhat?

**Comment by dsavineau** [comment]
I think that's a valid bug because the rhscon-agent is only a package present for RHCS 2 (Red Hat Ceph Cluster) so there's nothing for CentOS.
rhscon is the Red Hat Storage Console for Ceph which is using salt.

https://access.redhat.com/documentation/en-us/red_hat_storage_console/2.0/html-single/quick_start_guide/index

**Comment by JinsYin** [comment]
why do not check for subscription manager for agent install? @alfredodeza

<https://github.com/ceph/ceph-ansible/commit/640442bee60dd629e325e8790225e3bc6bc2e7ef#diff-1ef55a21610aedee375295e1491f4487>
