### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by XenGi** [ceph/ceph-ansible#4752]
**Is your feature request related to a problem? Please describe.**
We work with python3 for quite some time now especially with my ansible deployments. Now our team wants to deploy this ceph cluster with ansible too. Sadly this ansible repo works with python2.
With Python2 no longer being supported in a bit more then a month (1.1.2020), what are the plans to finally switch to python3?
I would gladly help. It's not hard to do, just a lot of work.

**Describe the solution you'd like**
I would propose a new branch to switch to python3 asap. I would help with that. I switched big codebases over a few times now and ansible is not as hard as pure python code.

**Describe alternatives you've considered**
The alternative to support python2 after 1.1.2020 is not a good idea. Any issues found in python2 won't be addressed. There will be no fixes. So there is no alternative.

**Additional context**
this is the only ansible repo that still uses python2 in our team. everything else was migrated to python3 long time ago.

Here's the message you probably all get.
```
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
```

The most important part is that even pip will drop support for python2. So at some point even installing the requirements.txt won't be possible and make this repo unusable with python2.

**Comment by dsavineau** [comment]
First, can you clarify what do you mean by "python3 support" ?

On the ansible controller ?
On the ceph nodes ?

Because we already support that at least on stable-4.0 and master branches for both cases.

On stable-3.2 branch I'm pretty sure that we can run ceph-ansible with ansible using python3 but it's not supported at all on ceph nodes (because the targeted distro on that branch only have python2).
And we won't make changes like that on this branch.

> Here's the message you probably all get.
> 
> ```
> DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
> ```

You only have this warning if you're using python2 with pip. At the end it's a user choice.
For instance I'm using virtualenv with python 3.7

> 
> The most important part is that even pip will drop support for python2. So at some point even installing the requirements.txt won't be possible and make this repo unusable with python2.

That's not true. New version won't work with python2 but older pip version will still be present.

**Comment by XenGi** [comment]
I digged a little deeper and found that too.
I was a bit confused because I found a note in the code saying that only supported python 2 and will try very hard to get it working on that.
So yeah python 3 works just fine. Sorry for the confusion.
