### ISSUE TITLE
Install(validate) fails if ansible is newer than v2.8

### ISSUE THREAD

**Issue by radonm** [ceph/ceph-ansible#4753]
Ansible host CentOS 7.7, all packages updated 2019-11-19, Ansible v2.9.0 from EPEL
Validation fails because ansible version is 2.9 and not 2.8.
After disabling v2.8 check install succeeds.

**Comment by dsavineau** [comment]
Because we currently only support ansible 2.8 on stable-4.0 and master branches.

So you have to stick to ansible 2.8 for now.

You can stick to older ansible release by using the rpm packages from https://releases.ansible.com/ansible/rpm/release/epel-7-x86_64/ instead of EPEL (because there's no versionning)

> After disabling v2.8 check install succeeds.

True but you could have other issues by running the current code with ansible 2.9 (like firewalld module https://github.com/ceph/ceph-ansible/pull/4705)
