### ISSUE TITLE
Need an updated place to download missing iscsi related rpms

### ISSUE THREAD

**Issue by ppbrown** [ceph/ceph-ansible#4831]
Issue 3706 mentions the following 3 URLs to use as repos to download rpms for the missing iscsi packages, such as tcmu-runner.

https://download.ceph.com/ceph-iscsi/latest/rpm/el7/
https://shaman.ceph.com/api/repos/tcmu-runner/master/latest/centos/7/
https://shaman.ceph.com/api/repos/python-rtslib/master/latest/centos/7/

Unfortunately.. the last 2 seem to have somehow become completely unusable. They just give me some kind of JSON dump, rather than a directory to download rpms from.

and I'm having difficulty decoding the reference given by
https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml#L2-L34

Could you please give an up to date URL for the last two?

**Comment by dsavineau** [comment]
I don't see why the last 2 urls are unusable because you need to know how shaman works.

If you add `/repo` at then end of the url then you will have the yum repository that you can consume.

That's exactly what is done automatically for you by in the ceph-iscsi-gw role [1][2]

[1] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml#L35
[2] https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-iscsi-gw/tasks/non-container/prerequisites.yml#L42

**Comment by ppbrown** [comment]
Thank you for the information.
It would be helpful if you updated the original ticket to mention that.
(Since thats what comes up when you do a google search for related issues)
