### ISSUE TITLE
use 'package' module instead of yum, apt and dnf

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#520]
New with Ansible 2.
Probably too soon since v2 just got released but this will definitely clean up the playbook :).

http://docs.ansible.com/ansible/package_module.html

**Comment by bengland2** [comment]
Yes, there is enormous replication of tasks to deal with upstart/systemd/sysvinit

**Comment by leseb** [comment]
This is only for package not module :). But at some point I'd like to deprecate some init systems too since all the distros are heading toward systemd.
This might happen when I'll switch from ansible versions.

**Comment by leseb** [comment]
Planned for September.

**Comment by leseb** [comment]
Once we have #1068 we can start refactoring

**Comment by guits** [comment]
Not sure we can refactor all `yum`, `apt` and `dnf` tasks because of many different cases and diverging package name between linux distributions (CentOS, RedHat, Debian, Ubuntu).

Even if some of them can be refactored easily, for instance :

https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/installs/install_on_redhat.yml#L2-L36

I'm wondering if we want to keep consistency on all these involved tasks or can we handle some case using `package` module while other cases are still using `apt`, `yum`,`dnf` modules ?

**Comment by leseb** [comment]
Let's refactor what we can and keep the `apt`, `yum`,`dnf` module if not possible.
