### ISSUE TITLE
Make Rados Gateway service dual stack capable (IPv4/IPv6)

### ISSUE THREAD

**Issue by imp1sh** [ceph/ceph-ansible#5385]
We tried to run Rados Gateway for our customers to let them have an S3 interface to the ceph storage. In order for this service to be highly available we looked at the documentation there is and finally decided to go a different way, i.e. Anycast (BGP), meaning the Rados Gateway host themselves have an instance of frr running which peers with Cumulus switches also running frr. ECMP is being used for load balancing. A failover check we still lack but is surely easy to be implemented with systemd timers.
This way we would not have to use a special software that handles virtual IP addresses like keppalived nor any kind of reverse proxy.
The problem is that we want to make the Rados Gateway dual stack capable which we can't because the playbook only supports one of those settings:

- radosgw_interface:
- radosgw_address:
- radosgw_address_block:

Neither of them results in an IPv6 and IPv4 dual stack service.

I tried the following two options, set directly in /etc/ceph/ourenv.conf

```
rgw frontends = beast endpoint=10.11.12.19:8080 endpoint=[2001:1:2:3::1]:8080
rgw frontends = beast port=8080
```

Both work for dual stack but the port variant is being more open, which would be fine for us, since we handle the firewalls with our own software instead of the playbook's.

This might be a relevant issue not only for Rados Gateway but also for other services. I'd really wish (playbook) developers would be more aware of users wanting IPv6 even more than IPv4 nowadays because it's just legacy. We actually thought about not using IPv4 at all but it soon turned out these playbooks do not support this - IMO more beautiful - approach.
I realize that it would mean quite a lot of work to be done in order to achieve dual stack or just full IPv6 support but in the long run it's inevitable.

**Comment by dsavineau** [comment]
At the moment ceph-ansible doesn't support IPv6 and IPv4 dual stack out of the box.

But you can still achieve that for radosgw with some workaround.

1/ By using the `[::]` address to bind on all IPv6 and IPv4 addresses (similar to `port=8080` only configuration). I've never tested this but as long as the radosgw daemon supports it then this should work.

```yaml
radosgw_address: '[::]'
```

But this isn't great from a security perspective.

2/ By using the `radosgw_frontend_options` variable for adding an additional `endpoint` option.

Something like:

```yaml
$ grep radosgw host_vars/*.yml
host_vars/cephaio-1.yml:radosgw_address: 192.168.100.12
host_vars/cephaio-1.yml:radosgw_frontend_options: "endpoint=[fdc2:328:750b:6983::7]:{{ radosgw_frontend_port }}"
host_vars/cephaio-2.yml:radosgw_address: 192.168.100.7
host_vars/cephaio-2.yml:radosgw_frontend_options: "endpoint=[fdc2:328:750b:6983::a]:{{ radosgw_frontend_port }}"
host_vars/cephaio-3.yml:radosgw_address: 192.168.100.6
host_vars/cephaio-3.yml:radosgw_frontend_options: "endpoint=[fdc2:328:750b:6983::f]:{{ radosgw_frontend_port }}"
```

You can either use IPv4 with `radosgw_interface`, `radosgw_address` or `radosgw_address_block` and IPv6 via `radosgw_frontend_options`. And the opposite is possible too.

Note that this is only working with one radosgw instance (the default configuration).

There's no plan for adding dual stack to ceph-ansible in the futur.


> I'd really wish (playbook) developers would be more aware of users wanting IPv6 even more than IPv4 nowadays because it's just legacy. We actually thought about not using IPv4 at all but it soon turned out these playbooks do not support this - IMO more beautiful - approach.

What do you mean exactly ? Because IPv6 only configuration is supported since multiple releases.

**Comment by imp1sh** [comment]
Workaround #1 does not work since the playbook tries to check the availability of the service, using the IP address. It would check against https://[::]:port which of course will fail.
Workaround #2 seems to work though, I need to do some more testing, especially with the ceritifcates, but that's a different topic.
