### ISSUE TITLE
Moving away from python2

### ISSUE THREAD

**Issue by amarao** [ceph/ceph-ansible#5462]
Python2 is dead and become more and more unwelcomed. Direct dependency on Python2 only is a sure way to cause headaches for all newer distributions.

**Describe the solution you'd like**
Total migration of all python code to Pyton3 or to version-agnostic python.

**Describe alternatives you've considered**
1. Invent time machine and go into year 2008.
2. Open issue in Python bugtracker and ask to revive python2.

Currently there are few pieces with a clear python2 dependency:
library/ceph_crush.py
library/ceph_volume.py
library/ceph_facts
library/ceph_add_users_buckets.py

~1600 lines of code.

**Comment by dsavineau** [comment]
> Python2 is dead and become more and more unwelcomed. Direct dependency on Python2 only is a sure way to cause headaches for all newer distributions

Where do you see direct dependency to python2 ?

Even if you sentence is right about the newer ditributions, we still need to consider old distribution that are still using python2.
As an exemple, Ceph is still supported on CentOS 7 which is python2 based.

> Total migration of all python code to Pyton3 or to version-agnostic python.

The ceph-ansible modules are python2/3 compatible.

**Comment by amarao** [comment]
1. If those modules are python2/3 compatible, why they have shebang if '/usr/bin/python'?
```
library/ceph_crush.py:#!/usr/bin/python
library/ceph_volume.py:#!/usr/bin/python
library/ceph_add_users_buckets.py:#!/usr/bin/python
library/ceph_facts:#!/usr/bin/python
```

2. There is `raw_install_python.yml` (imported from site.yml.sample) which installs python (2) packages and causes a mess on Ubuntu Focal because of the python2.

**Comment by dsavineau** [comment]
> If those modules are python2/3 compatible, why they have shebang if '/usr/bin/python'?

Do you know how the ansible module are working ?

Because the shebang isn't used at all, has no effect and probably legacy from previous ansible release where python3 wasn't supported.

The ansible modules are copied on the target host and executed with the discovered python interpreter which can be either python2 or 3.

> There is raw_install_python.yml (imported from site.yml.sample) which installs python (2) packages and causes a mess on Ubuntu Focal because of the python2.

That one is valid because we don't test with Ubuntu focal so we may want to change [1] with python3-simplejson. But that would also mean you're using a node without python3 installed. I personally think that python should always be installed before any ansible execution.

[1] https://github.com/ceph/ceph-ansible/blob/master/raw_install_python.yml#L48
