### ISSUE TITLE
osd_auto_discovery not working on (our) kvm instances

### ISSUE THREAD

**Issue by zmc** [ceph/ceph-ansible#556]
I'm working on getting ceph-ansible testable via [teuthology](https://github.com/ceph/teuthology). The ``osd_auto_discovery`` feature isn't working on our KVM-based virtual machines. It *might* be working in our OpenStack test lab. I'm attempting to figure out what is causing the difference in behavior but I figured I should file an issue while I do that, in case there is a fix obvious to someone more experienced with ceph-ansible.

The error I see is:
``error while evaluating conditional: item.0.rc != 0 and item.1.rc != 0 and journal_collocation and not osd_auto_discovery``

Here is an example of the same job [executed on OpenStack](http://teuthology.ovh.sepia.ceph.com/teuthology/zack-2016-02-22_16:20:20-ceph-ansible-master---basic-openstack/3360/teuthology.log) vs. [executed on KVM](http://qa-proxy.ceph.com/teuthology/zack-2016-02-22_08:26:37-ceph-ansible-master---basic-vps/20458/teuthology.log).

That's a ton of output so I'll attempt to isolate some relevant things. First, I'm using a [separate branch of ceph-ansible with extra debugging](https://github.com/ceph/ceph-ansible/compare/wip-teuthology).

Here is just the [debug from OpenStack](https://gist.github.com/zmc/1ef9daa99c0c768b1da8/raw/4bf7a4107a8f27849523cc71880d010f290df7fb/ovh-debug.txt) vs. the [debug from KVM](https://gist.github.com/zmc/1ef9daa99c0c768b1da8/raw/4bf7a4107a8f27849523cc71880d010f290df7fb/vps-debug.txt)

``combined_parted_results.results`` and ``combined_ispartition_results.results`` are very different between the two instances. What I haven't unraveled yet is *why* - aside from the obvious difference in device counts.

**Comment by leseb** [comment]
@zmc at a first glance, if the output is so different is mainly because the KVM env has more disks than the OpenStack. On OpenStack, you seem to only have a single drive `/dev/vda` where on KVM you have `/dev/vda`, `/dev/vdb`, `/dev/vdc`, `/dev/vdd`.

I just figured out that this https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/check_devices.yml#L21-L30 is useless while using `osd_auto_discovery`, the device list will always be a raw device. So this shouldn't run.
I'll push some changes in your branch, if you can try that out since I can't reproduce this with vagrant (somehow :/)
