### ISSUE TITLE
Assumptions about consistent container runtime in a Ceph cluster running mixed OS versions

### ISSUE THREAD

**Issue by oneswig** [ceph/ceph-ansible#6102]
**Bug Report**

I am working with a containerised deployment that is migrating from CentOS 7 (and Docker) to CentOS 8 (and Podman).  It does not appear possible to deploy MGRs or MDSs on the new CentOS 8 image due to an assumption that all nodes have the same container runtime.  This is causing problems when forming delegated commands to run on other cluster hosts.

In the role `ceph-mgr`, task `get keys from monitors`, I see errors of the form:

```
failed: [host6 -> host5] (item={u'path': u'/var/lib/ceph/mgr/ceph-host6/keyring', u'name': u'mgr.host6', u'copy_key': True}) => changed=false  
  ansible_loop_var: item 
  cmd: podman exec ceph-mon-host5 ceph --cluster ceph auth get mgr.host6 
  item: 
    copy_key: true 
    name: mgr.host6 
    path: /var/lib/ceph/mgr/ceph-host6/keyring 
  msg: '[Errno 2] No such file or directory' 
  rc: 2 
```

The issue being that `host5` is running Docker and `host6` is running Podman.

How to reproduce it (minimal and precise):

It should be relatively easy to reproduce by adding a new host running CentOS8/Podman to a cluster running CentOS7/Docker.

**Environment**:
* OS is being upgraded from `CentOS 7.8.2003` to `CentOS 8.2.2004`
* Docker RPM is `docker-1.13.1-203`, Podman RPM is `podman-1.6.4-10`
* Ansible version is `2.9.15`
* ceph-ansible version is stable-4.0
* Ceph version is Nautilus 14.2.15

**Comment by dsavineau** [comment]
Hi Stig,

Unfortunatly that's a known issue as we assume the entire cluster is running the same OS.

The main issue is that we are delegating some commands by using the `container_binary` global variable instead of the scoped one to the delegated node (`container_binary` vs `hostvars[xxx]['container_binary']`). I think there's a lot of places in the roles where this need to be changed.

As a temp workaround, did you try to add a symlink podman->docker on host5 ?
