### ISSUE TITLE
How to install older version ceph 

### ISSUE THREAD

**Issue by dbenduga** [ceph/ceph-ansible#6162]
Hi Team,

We have installed 14.2.7 cluster a year ago using ansible playbook. Now planning to upgrade it to latest version.

Cluster is in production so before upgrade it in prod env. I want to test it in test env.. so want to install same version of ceph.

Is there any file where we can mention specific ceph version ?

Regards,
Dipesh

**Comment by dsavineau** [comment]
That's indeed not possible out of the box.

With Octopus it should be possible since each minor release is stored in a dedicated rpm/deb repository so you don't have multiple versions in the same repo.

That said, it is not impossible but would required some manual step before the ceph-ansible execution for nautilus.

You would need to install manually the repository and pin (debian) the packages or use yum versionlock (centos) for your specific release.
