### ISSUE TITLE
4.0.43: No package matching 'python-routes' is available. (Ubuntu 20.04)

### ISSUE THREAD

**Issue by cloudguy23** [ceph/ceph-ansible#6201]
**Bug Report**

What happened:  

Trying to deploy an additional nautilus monitor / manager on Ubuntu 20.04 LTS using ceph-ansible 4.0.43

What you expected to happen:

A successful deployment.

How to reproduce it (minimal and precise):
When running site.yml playbook, ceph-ansible throws:

TASK [ceph-mgr : install routes python library for dashboard module] ******************************************************************************************************
task path: /opt/playbooks/ceph/ceph-ansible-4.0.43/roles/ceph-mgr/tasks/pre_requisite.yml:26
Tuesday 19 January 2021  14:58:58 -0500 (0:04:16.246)       0:08:07.678 ******* 
FAILED - RETRYING: install routes python library for dashboard module (3 retries left).
FAILED - RETRYING: install routes python library for dashboard module (2 retries left).
FAILED - RETRYING: install routes python library for dashboard module (1 retries left).
fatal: [storprod01mon05.yyz01.o]: FAILED! => changed=false 
  attempts: 3
  msg: No package matching 'python-routes' is available

20.04 has python3-routes package available.   Had a look through #3997 however doesn't seem to be related.

**Environment**:
* OS (e.g. from /etc/os-release):  Ubuntu 20.04 LTS
* Kernel (e.g. `uname -a`): 
* Docker version if applicable (e.g. `docker version`):
* Ansible version (e.g. `ansible-playbook --version`):
* ceph-ansible version (e.g. `git head or tag or stable branch`):
* Ceph version (e.g. `ceph -v`):

**Comment by dsavineau** [comment]
Nautilus isn't supported on Ubuntu 20.04 (focal) but only 18.04 (bionic) and 16.04 (xenial).

Nautilus is still built with python 2 support whereas Ubuntu 20.04 supports python3.

I think Octopus is the first release to support Ubuntu 20.04 due to the python3 switch.

**Comment by cloudguy23** [comment]
Thanks for the reply.   How would one go about upgrading from Nautilus -> Octopus using ceph-ansible?

My deployment is CentOS 7 based.   Was thinking of changing OS to Ubuntu 20.04 using ceph-ansible then upgrading packages.   

Would a recommended approach be to use ceph-ansible 5.0 to deploy replatformed hosts?

**Comment by dsavineau** [comment]
> Thanks for the reply. How would one go about upgrading from Nautilus -> Octopus using ceph-ansible?

By running the upgrade playbook [1][2]

The workflow should be something like.

- clone ceph-ansible with stable-4.0 branch and deploy the inital cluster with either site.yml or site-container.yml playbooks.
- switch to ceph-ansible stable-5.0 branch and update your {group,host}_vars
- run the upgrade playbook to upgrade the cluster to octopus.

> My deployment is CentOS 7 based. Was thinking of changing OS to Ubuntu 20.04 using ceph-ansible then upgrading packages.

First, ceph-ansible isn't design to change OS and doesn't play well with mixed OS versions.

Then, that's a tricky one since Ubuntu 20.04 isn't supporting for Nautilus so you can't switch to that distro before upgrading.

But upgrading to Octopus on CentOS 7 could also have multiple issues since there are missing python3 dependencies (especially with ceph mgr dashboard) for that distro.

One solution could be to use containers instead of package deployment. When using containers you don't need instead any
dependencies except the container engine itself.

The workflow could be:

switch the CentOS 7 / Nautilus cluster to containerized deployment by running the dedicated playbook [3] on stable-4.0 branch.

at this point you can either upgrade to Octopus on CentOS 7 (since you don't have the dependencies issue because the container image is based on CentOS 8) or reinstall each node with Ubuntu.

> Would a recommended approach be to use ceph-ansible 5.0 to deploy replatformed hosts?

Well if you don't mind about loosing your old cluster then it would be easier but it depends on your expectations.

[1] https://github.com/ceph/ceph-ansible/blob/stable-5.0/infrastructure-playbooks/rolling_update.yml
[2] https://docs.ceph.com/projects/ceph-ansible/en/latest/day-2/upgrade.html
[3] https://github.com/ceph/ceph-ansible/blob/stable-4.0/infrastructure-playbooks/switch-from-non-containerized-to-containerized-ceph-daemons.yml

**Comment by cloudguy23** [comment]
Thank you @dsavineau ..  Sounds like containerization is the way to go.   Will work towards proceeding that way.
