### ISSUE TITLE
stable-4: nfs-ganesha-rgw and ceph-radosgw fail to install on CentOS 8

### ISSUE THREAD

**Issue by renich** [ceph/ceph-ansible#6686]
**Bug Report**

What happened: 

While installing Ceph with `ceph-ansible`; using branch `stable-4`, the nfs tasks fail due to `nfs-ganesha-rgw` missing some dependencies.

What you expected to happen: 

The packages should just install properly; as with `stable-5` (same config works fine in it)

How to reproduce it (minimal and precise):

if we assume we have a working config in `group_vars/*`:

```sh
# set the config
cat << 'EOF' > group_vars/nfss.yml

---
copy_admin_key: true
ceph_nfs_enable_service: true
ceph_nfs_ceph_export_id: 20133
ceph_nfs_ceph_pseudo_path: "/"
ceph_nfs_ceph_protocols: "3,4"
ceph_nfs_ceph_access_type: "RW"
ceph_nfs_ceph_user: "S3_USER"

# run the role
ansible-playbook -i inventory/staging/hosts --limit='nfss' site.yml
```

A short-hand way would be: 

```sh
# login to the relevant ceph node:
# ssh centos8-ceph-0

# make sure the repo is in place
# cat /etc/yum.repos.d/nfs_ganesha_stable.repo 
[nfs_ganesha_stable]
baseurl = http://download.ceph.com/nfs-ganesha/rpm-V2.8-stable/nautilus/$basearch
gpgcheck = 1
gpgkey = https://download.ceph.com/keys/release.asc
name = nfs-ganesha stable repo

# try installing both packages
# dnf install nfs-ganesha-rgw ceph-radosgw
Last metadata expiration check: 0:23:05 ago on Thu 08 Jul 2021 03:19:48 AM UTC.
Package ceph-radosgw-2:14.2.22-0.el8.x86_64 is already installed.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides libnfsidmap.so.0()(64bit) needed by nfs-ganesha-rgw-2.8.1.2-0.1.el7.x86_64
  - nothing provides liburcu-bp.so.1()(64bit) needed by nfs-ganesha-rgw-2.8.1.2-0.1.el7.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Share your group_vars files, inventory and **full** ceph-ansibe log

I will if you consider it necessary. I think the issue is pretty straight forward. There are no el8 packages for 2.8 and it's trying to install these. 

**Environment**:
* OS (e.g. from /etc/os-release):

```
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"
```

* Kernel (e.g. `uname -a`):

```
Linux centos8-ceph-0 4.18.0-315.el8.x86_64 #1 SMP Mon Jun 28 19:09:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

* Ansible version (e.g. `ansible-playbook --version`):

```
ansible-playbook 2.9.23
  config file = /home/renich/src/ceph-ansible/ansible.cfg
  configured module search path = ['/home/renich/src/ceph-ansible/library']
  ansible python module location = /home/renich/src/ceph-ansible/venv/lib/python3.9/site-packages/ansible
  executable location = /home/renich/src/ceph-ansible/venv/bin/ansible-playbook
  python version = 3.9.5 (default, May 14 2021, 00:00:00) [GCC 11.1.1 20210428 (Red Hat 11.1.1-1)]
```

* ceph-ansible version (e.g. `git head or tag or stable branch`):

```
(venv) [renich@introdesk ceph-ansible]$ git branch 
  master
* stable-4.0
  stable-5.0
  stable-6.0
```

* Ceph version (e.g. `ceph -v`):

```
ceph version 14.2.22 (ca74598065096e6fcbd8433c8779a2be0c889351) nautilus (stable)
```

**Comment by dsavineau** [comment]
> I think the issue is pretty straight forward. There are no el8 packages for 2.8 and it's trying to install these.

And there's nothing we can do about this.

nfs-ganesha packages V2.8 are available only for nautilus on EL7 [1][2]
Since octopus and V3.3, you have both EL7 and EL8 packages [3][4]

If you want ganesha V2.8 with nautilus then use an EL7 node for that service or you can consider using containers [5]

[1] https://download.ceph.com/nfs-ganesha/rpm-V2.8-stable/nautilus/
[2] https://github.com/ceph/ceph-ansible/blob/stable-4.0/roles/ceph-defaults/defaults/main.yml#L138
[3] https://download.ceph.com/nfs-ganesha/rpm-V3.3-stable/octopus/
[4] https://github.com/ceph/ceph-ansible/blob/stable-5.0/roles/ceph-defaults/defaults/main.yml#L140
[5] https://docs.ceph.com/projects/ceph-ansible/en/latest/installation/containerized.html

**Comment by renich** [comment]
That's odd. You support nautilus on el8: http://download.ceph.com/rpm-nautilus/el8/x86_64/ and everything works fine, only nfs-ganesha doesn't. 

That said, I found the nfs-ganesha RPMs in CentOS repo: https://mirrors.edge.kernel.org/centos/8/storage/x86_64/nfsganesha-28/Packages/n/

Why don't you support it?

**Comment by dsavineau** [comment]
> That's odd. You support nautilus on el8: http://download.ceph.com/rpm-nautilus/el8/x86_64/ and everything works fine, only nfs-ganesha doesn't.

I know, but again we can't really do anything about that except a note in the documentation or add a check for CentOS 8 + ganesha in non containerized deployment and stop the deployment.
This was mentioned in the commit introducing CentOS 8 support for nautilus [1] but it's clearly not visible for users.

> That said, I found the nfs-ganesha RPMs in CentOS repo: https://mirrors.edge.kernel.org/centos/8/storage/x86_64/nfsganesha-28/Packages/n/
> 
> Why don't you support it?

Because we only support ceph and ganesha builds from download.ceph.com when using ceph_origin: repository and ceph_repository: community

As an example, V2.8 on that repository has been built against nautilus while we don't have any idea of the ceph version used in the CentOS SIG storage for ganesha 2.8

Another one is that the `nfs-ganesha-rgw` package doesn't exist in the CentOS SIG storage for ganesha 2.8 whereas on download.ceph.com it does.
So the SIG storage repository doesn't provide the rgw FSAL for ganesha.

[1] https://github.com/ceph/ceph-ansible/commit/47f24ec0473bd9464369235b7404d3f143090486

**Comment by renich** [comment]
You're right @dsavineau. Thank you for explaining.
