### ISSUE TITLE
ceph.conf template has defaults that override better defaults in jewel

### ISSUE THREAD

**Issue by jdurgin** [ceph/ceph-ansible#693]
There are a bunch of tunings and settings in ceph.conf that make sense to apply to older version of ceph, but are replaced by better defaults in jewel. As they change, it would be better to let the newer ceph defaults come into effect, instead of always overriding them in ceph.conf.

It would be great to have a more minimal ceph.conf for jewel and later - perhaps just via a 'no tuning' option - that does not put any of 'rbd default', 'rbd cache', 'osd *', 'filestore *', 'debug *' settings into ceph.conf (with the exception of setup config, like journal size and mkfs options if those are still needed).

**Comment by vasukulkarni** [comment]
perhaps its better to have 'no tuning' which in general doesn't set any defaults for any section and let the user do all the setting.

**Comment by leseb** [comment]
@jdurgin thanks for raising this one up.
Actually I've been thinking of removing entirely most of the default since they tend to pollute a bit the `ceph.conf`. I'm saying 'pollute' because we recently release the ability to dynamically overwrite the content of the `ceph.conf` using simple variables, see: https://github.com/ceph/ceph-ansible/blob/master/group_vars/all.sample#L306-L321
The reason why we have so many defaults is that at some point I wanted to highlight some of the best config options that users might want to tweak.
If I still haven't reworked this part is that changing the `ceph.conf`will trigger an unnecessary restart of all the ceph daemons... Moreover, this will reset most the settings that users implemented.

Perhaps I can do this for the next release of ceph-ansible and then add a major warning for all the running users.
Let me give a shot at purging the `ceph.conf` a bit, will put you in cc for review.
