### ISSUE TITLE
Permissions of DB and Wal  devices

### ISSUE THREAD

**Issue by feeyman** [ceph/ceph-ansible#7140]
Hello, when I use tag **6.0.25.4**, the following problem occurs. Only one OSD on each machine is created successfully; I don't know if my configuration is wrong; Hope to get your reply, thank you very much.
all.yml

<img width="661" alt="截屏2022-04-12 22 33 19" src="https://user-images.githubusercontent.com/24524775/162986874-db8062f1-971c-4e1c-992e-a37af3e4e930.png">

osds.yml
![image](https://user-images.githubusercontent.com/24524775/162987105-7077a951-4d94-4070-bbfc-932c7fc0a5ec.png)

The Result:
<img width="726" alt="截屏2022-04-12 22 37 52" src="https://user-images.githubusercontent.com/24524775/162988027-57deb93b-0460-4497-a614-e6e37a12b4af.png">
<img width="1168" alt="截屏2022-04-12 22 41 29" src="https://user-images.githubusercontent.com/24524775/162988514-07d50f10-78ae-421b-94ad-2f3d4b470a91.png">

**Environment**:
* OS (centos 8): 8.4.2105

* Kernel (e.g. `uname -a`):4.18.0-305.3.1.el8.x86_64
* Ansible version (e.g. `ansible-playbook --version`):2.9
* ceph-ansible version (e.g. `git head or tag or stable branch`):6.0.25.4
* Ceph version (e.g. `ceph -v`):16.2.7

**Comment by guits** [comment]
You are reproducing an issue we have already hit a while ago in Red Hat downstream CI only.
It was showing up so intermittently and only in that CI that we've never been able to investigate seriously and fix it... 😖 

If I remember well it's a race condition in ceph-volume because of a udev event triggered from within the ceph-volume code.

@feeyman how often would you say you hit this issue?
