### ISSUE TITLE
Replace a failed OSD Drive procedure.

### ISSUE THREAD

**Issue by grharry** [ceph/ceph-ansible#7282]
Hello ceph people! 

Help required here. 
It's not clear at all to me how to replace a failed Disk Drive ( luminus ). 
In Other Words, I Cannot locate a clear  procedure or a how-to  stating the steps to  replace  failed drives  using ansible   from a CEPH storage system. 

Am I the only one with this problem ? 
Regards, 
Harry.

**Comment by jeevadotnet** [comment]
Hi @grharry 

I use ceph-ansible on an almost weekly basis to replace one of our thousands of drives. 

I'm currently running pacific, but started of the cluster om luminous so it was basically the same. 

You will have issues if your inventory's disk placement is not 100% configured correctly, in my instance I used manual disk placements and not osd_autodiscovery from `osds.yml` (since osd_autodiscovery is not recommended). 

E.g. one node would be 
[nodepool02]
B-02-40-cephosd.maas osd_objectstore=bluestore devices="[ '/dev/sda', '/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh', '/dev/sdi', '/dev/sdj', '/dev/sdk', '/dev/sdl', '/dev/sdm', '/dev/sdn', '/dev/sdo', '/dev/sdp', '/dev/sdq', '/dev/sdr', '/dev/sds', '/dev/sdt', '/dev/sdu', '/dev/sdv', '/dev/sdw', '/dev/sdx' ]" dedicated_devices="[ '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1' ]"

You will require the same amount of `bluestore_devices` for every `dedicated_devices` (rockswal/db offload), otherwise you will have issues with the playbook.

If you're sure everything is correct you can just run:

`ansible-playbook -i /opt/ceph-ansible/inventory -e 'ansible_python_interpreter=/usr/bin/python3' infrastructure-playbooks/shrink-osd.yml -e osd_to_kill=1592` 

Where `osd_to_kill` is your corresponding OSD that is faulty. This will format the disk, and remove it from ceph crush/ceph completely, no other action required. 

If the disk is still readable from time to time, i.e. not completely dead, I generally weigh it out manually, `ceph osd reweight osd.x 0` which is the equivalent of setting the osd out. It will still try to read data from the disk while draining it for quicker backfilling. Once it is drained, I run `shrink-osd.yml`. In the even that the disk is completely dead just run the `shrink-osd.yml` as above. 

If you don't know the faulty OSD and only the harddrive serial number from IPMI/IDRAC/ILO you can use `ceph device ls | grep 'serial number'` to get the corresponding OSD value, or `ceph-volume inventory` from within one of your osds/mds/mon/mgr docker containers `exec -it ... /bin/bash`

Once the disk is replaced with a new one you can run 
`ansible-playbook -i /opt/ceph-ansible/inventory -e 'ansible_python_interpreter=/usr/bin/python3' site-container.yml --limit=HOSTwithNEWdisk` , `--limit=` it to the ceph osd node with the new/replaced disk.

If you run `site-container.yml` and it completes successfully but you don't see your new(replacement OSD) added to ceph, I generally `ssh` to the host with the new disk and run an `lsblk -p` , find the new disk `/dev` value and run, `dd if=/dev/zero of=/dev/sdX bs=1M` #replace X with the target drive letter. 

Then proceed to run: `ansible-playbook -i /opt/ceph-ansible/inventory -e 'ansible_python_interpreter=/usr/bin/python3' site-container.yml --limit=HOSTwithNEWdisk`, again. 

`ansible_python_interpreter` is not required, depending on your environment

**Comment by grharry** [comment]
Wow !!! 
At LAST! 
Thank you so much !!!! 
I owe U at least a BEER !!! 
Regards, 
Harry!

**Comment by guits** [comment]
> E.g. one node would be in your inventory
>
> ```
> [nodepool02]
> B-02-40-cephosd.maas osd_objectstore=bluestore devices="[ '/dev/sda', '/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh', '/dev/sdi', '/dev/sdj', '/dev/sdk', '/dev/sdl', '/dev/sdm', '/dev/sdn', '/dev/sdo', '/dev/sdp', '/dev/sdq', '/dev/sdr', '/dev/sds', '/dev/sdt', '/dev/sdu', '/dev/sdv', '/dev/sdw', '/dev/sdx' ]" dedicated_devices="[ '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1' ]"

@jeevadotnet I think having as many `dedicated_devices` as `devices` is no longer a requirement.
This 1:1 relation disappeared after we dropped ceph-disk support (stable-4.0).
If you take a look at this task in the role `ceph-facts` you will see that we use the filter `| unique`

https://github.com/ceph/ceph-ansible/blob/f288364c5c268e61d49165704900e8e01ca643c8/roles/ceph-facts/tasks/devices.yml#L45-L50

**Comment by guits** [comment]
@jeevadotnet very useful feedback. I'm considering writing a documentation ouf of it 🙂 
Thanks!

**Comment by jeevadotnet** [comment]
> > E.g. one node would be in your inventory
> > ```
> > [nodepool02]
> > B-02-40-cephosd.maas osd_objectstore=bluestore devices="[ '/dev/sda', '/dev/sdb', '/dev/sdc', '/dev/sdd', '/dev/sde', '/dev/sdf', '/dev/sdg', '/dev/sdh', '/dev/sdi', '/dev/sdj', '/dev/sdk', '/dev/sdl', '/dev/sdm', '/dev/sdn', '/dev/sdo', '/dev/sdp', '/dev/sdq', '/dev/sdr', '/dev/sds', '/dev/sdt', '/dev/sdu', '/dev/sdv', '/dev/sdw', '/dev/sdx' ]" dedicated_devices="[ '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1', '/dev/nvme0n1' ]"
> > ```
> 
> @jeevadotnet I think having as many `dedicated_devices` as `devices` is no longer a requirement. This 1:1 relation disappeared after we dropped ceph-disk support (stable-4.0). If you take a look at this task in the role `ceph-facts` you will see that we use the filter `| unique`
> 
> https://github.com/ceph/ceph-ansible/blob/f288364c5c268e61d49165704900e8e01ca643c8/roles/ceph-facts/tasks/devices.yml#L45-L50

Will try it today when rebuilding testbed with your recommendation as per #7283 , however maybe I did it previously wrong, but tested `luminous` and `octopus` with the `many:1` relation but then it only created a partition for my `/dev/sda`.


> @jeevadotnet very useful feedback. I'm considering writing a documentation ouf of it 🙂 Thanks!
Haha, pleasure, you always great in helping out here and teaching me the 'way of the ceph', so I eventually over time I've learned enough to be able to reply to other people's issues.

**Comment by grharry** [comment]
Hello Again! 
I need some clarification. 
On my ceph instalation ( luminous ). 
I've got 4 OSDs DOWN ( waiting for replacement drives )  
and my current pg status shows 
5 pgs inactive, 3 pgs down, 2 pgs peering, 12 pgs stale

querying the down pg's they seem to be stuck  by the dead OSD's

Do I proceed with .....  shrink-osd.yml -e osd_to_kill=xxx  first?  or   ceph pg force_create_pg <pgid>  with the id's of down pgs ?? 
Thank's again for your help! 
Harry.
