### ISSUE TITLE
ansible-ceph galaxy roles

### ISSUE THREAD

**Issue by mattt416** [ceph/ceph-ansible#740]
Hi @leseb ,

Apologies if I've missed documentation etc, but I see https://github.com/ceph/ansible-ceph-common, https://github.com/ceph/ansible-ceph-mon, https://github.com/ceph/ansible-ceph-osd, etc. have not been updated with the changes going into this repo.  Should we no longer be using those individual repos (or ansible galaxy roles)?

Any information appreciated.

--Matt

**Comment by leseb** [comment]
@mattt416 thanks for highlighting this. Since I brought the symlink for ceph-common to ceph.ceph-common this broke the git subtree script. For some reasons, it is now generating an entire new tree of commits and will likely overwrite what you are using. Other repos can be updated, however I'm just a bit worried about updating them since they all depend on ceph-common.
I haven't still had the time to have a look at this again.

I'll see what I can do next week though as I'm not planning on stopping on updating those repos.

**Comment by vincepii** [comment]
This puzzled me as well!
So for the moment I will use the roles from this repo without ansible-galaxy :)!

**Comment by leseb** [comment]
sorry guys, I really need to find this time to get into this.

**Comment by mattt416** [comment]
Thanks @leseb.  We'd love to bump rpc-openstack to use newer SHAs so that we don't start to fall too far behind.  Let me know if I can be of help in any way.

**Comment by leseb** [comment]
Thanks @mattt416 cool, I'll try to fix this one more time. If I can't we will start with newer SHAs.
I'll let you know the outcome, so we can plan a smooth transition on your side.

wdyt?

**Comment by mattt416** [comment]
Hi @leseb, so from my testing when I run `git subtree split --prefix=roles/ceph-common -b ceph-common` the ceph-common branch looks right but has tons of old commit history from before the ceph-common role was introduced.  It looks like this may be fallout from when roles/ceph-common was renamed to roles/ceph.ceph-common and back again, though I am speculating at this point.

The good news is that the ceph-common branch includes the SHA we're pointing at, but the history now doesn't match what is on https://github.com/ceph/ansible-ceph-common, which may cause some issues for people.

I'm not sure what options we have at this point.  Anyone else out there with a solid git understanding that is able to determine what is happening here?

Thanks!

--Matt

**Comment by mattt416** [comment]
Thanks for getting the ceph galaxy roles back in order, @leseb !
