### ISSUE TITLE
do not create symlinks for systemd

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#779]
The rbd-mirror role does this in one of its tasks:

    - name: enable systemd unit file for the rbd mirror service (systemd after hammer)
      file:
        src: /usr/lib/systemd/system/ceph-rbd-mirror@.service
        dest: "/etc/systemd/system/multi-user.target.wants/ceph-rbd-mirror@{{ ceph_rbd_mirror_local_user }}.service"
        state: link
      changed_when: false
      failed_when: false
      when:
        - use_systemd
        - is_after_hammer

That should not be needed, if it is needed then the packaging of rbd-mirror/ceph is at fault

**Comment by alfredodeza** [comment]
Hrmn, it looks like we do this all over the place. @leseb is there a specific reason we were not using:

    - service: name=ceph-rbd-mirror enabled=yes

**Comment by ktdreyer** [comment]
(Note that on Ubuntu Xenial, `/usr/lib/systemd` does not even exist, so I'm a big :+1: to seeing this manage-symlinks-by-hand thing go away)

**Comment by leseb** [comment]
I recently discovered that this wasn't needed since the packages are taking care of this.
I'm for removing those symlinks.

I actually recently removed it from the mon, the only issue is that the ansible "service" module doesn't seem to enable the services properly... So I had to do this: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-mon/tasks/start_monitor.yml#L30-L36

@alfredodeza do you mind taking care of the PR?
Thanks!

**Comment by ktdreyer** [comment]
In general if you see things that the packaging *should* be doing, *please* file tickets instead of adding workarounds in ceph-ansible! then we all benefit :)

**Comment by leseb** [comment]
@ktdreyer it's not an issue with the packaging, it was a mistake :). However somehow this made the job quite well.

**Comment by ktdreyer** [comment]
Ok, thanks

**Comment by alfredodeza** [comment]
@leseb thank you for the pointers, I will take care of it.

**Comment by leseb** [comment]
@alfredodeza Thanks!
