### ISSUE TITLE
Prefix variable name with role name

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#78]
For consistency and readability sake, it would be nice to rename all the variables and prefix them with the role name where they are used in.

**Comment by leseb** [comment]
Unfortunately, I think we have reached a point where we can't implement this...

**Comment by vincepii** [comment]
Any chance this can be reconsidered?

If this is done improperly it can lead to disasters: an unaware user pulls from master and all of a sudden his variables do not override the defaults anymore.

But maybe there are safer ways, like an official fork for a 2.0 release cycle?

**Comment by leseb** [comment]
Well that's a though one, the next branch will drop support for 1.9.4 , so we can not have this one yet.
As you mentioned I think most of the users will be impacted by the change and it's hard to have something backward compatible.
We could potentially provide a transition script...
That's the only thing I can think of.

**Comment by vincepii** [comment]
A transition script plus a check for "old" variables being still defined, which in case stops the playbook suggesting the user to run the script, could help.
It's still a huge impact.

OTOH, an accidental override caused by too generic names can also have big consequences (e.g., for users that have more than one role sharing e.g., some group_vars).
Without namespaced variable names, it's easy to unintentionally redefine variables with values that refer to other roles (I'm thinking about generic variable names such as "devices" or "pools").
