### ISSUE TITLE
error when ceph-disk fails to prepare a device/partition (again)

### ISSUE THREAD

**Issue by alfredodeza** [ceph/ceph-ansible#835]
I am starting to think we should just really fail when the return code is non-zero.

https://bugzilla.redhat.com/show_bug.cgi?id=1342117

**Comment by alfredodeza** [comment]
@leseb I can't remember why we were always ignoring return codes when calling `ceph-disk prepare` 

We either need to always fail, or add another check in stderr/stdout to fail. This time it would be when ceph-disk has a Traceback

**Comment by leseb** [comment]
@alfredodeza I think we were ignoring return codes just because we thought it was fine to have "most" of the OSDs configured. However we recently chose a different path.
So yes we should be failing if something does not get configured the way we asked.

If the desired state is not reached then we must fail :).

**Comment by alfredodeza** [comment]
awesomeness. I will get a fix out shortly.

**Comment by leseb** [comment]
Thanks!
