### ISSUE TITLE
plugins/actions/config_template.py doesn't work with ansible2.2

### ISSUE THREAD

**Issue by khappone** [ceph/ceph-ansible#893]
```
TASK [ceph.ceph-common : generate ceph configuration file] *********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: _make_tmp_path() takes exactly 2 arguments (1 given)
fatal: [storage0111]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

```

```
ansible --version
ansible 2.2.0
```

In ansible in the plugins/action/__init__.py file:
    def _make_tmp_path(self, remote_user):

In earlier versions it looked like:
    def _make_tmp_path(self):

**Comment by leseb** [comment]
I'm not familiar with this code, I'll let @cloudnull chime in :)

**Comment by cloudnull** [comment]
sorry was afk, I've not tried Ansible 2.2 as it's still in development. However i now have a reason to give it a go. I'll post back shortly.

**Comment by cloudnull** [comment]
TODO:

- [ ] Check that ``config_template`` is functional in "v2.1.1.0-0.5.rc5" which is the upcoming stable release
- [ ] Check that ``config_template`` is functional in "master" which is the head of development for version for "2.2.x".

**Comment by cloudnull** [comment]
With the initial testing I've been able to get it to work without incident for both the head of 2.1.1 and 2.2.x development. @khappone your deploying on an earlier release before this commit went in [ https://github.com/ceph/ceph-ansible/commit/6dea2e2f89046df63a234c1f6df507bfbebae004 ]?  If so that would make sense because we pushed an update to the plugin at that time which addressed that issue. This was changed [ https://github.com/ceph/ceph-ansible/commit/6dea2e2f89046df63a234c1f6df507bfbebae004#diff-e27bcc569a39c2de72fb1679dffb764dL261 ] to [ https://github.com/ceph/ceph-ansible/commit/6dea2e2f89046df63a234c1f6df507bfbebae004#diff-d332bef1b78a297caccb463158b8f76bR481 ] which used a try/except to support early "2.0" and "2.1". Check the version you have and the template on disk and let me know what you find out. If there's something a-miss please let me know.

**Comment by cloudnull** [comment]
@khappone This is the repo I've been using to exercise the ``config_template`` bits: https://github.com/cloudnull/testing_config_template -- IDK if that helps you in any way but I figured I'd share it just in case.

**Comment by khappone** [comment]
My apologies. You are completely correct. The problem is that I use the roles directly and I don't use ceph-ansible to coordinate the roles. The plugins/actions/config_template.py from the ceph-common role has this problem, not the one in the top-level ceph-ansible. Is the one in the ceph-common role still used for anything? The role documentation still mentions that it should be used.

**Comment by leseb** [comment]
@khappone sorry for the confusion, I just pushed https://github.com/ceph/ceph-ansible/commit/2ca0734c385dda3cf8d8c6567ba971617995407e and updated ansible-ceph-common. Closing this.
