### ISSUE TITLE
Deploy ceph using partitions for journal and osds

### ISSUE THREAD

**Issue by vincepii** [ceph/ceph-ansible#895]
We are using the roles to deploy ceph with partitions as follows:

```
raw_multi_journal: true

devices:
 - /dev/sdb3

raw_journal_devices:
 - /dev/sdb2
```

During the deployment process, the ceph osd prepare step is skipped because the `check if the device is a partition` task (which runs `"echo '{{ item }}' | egrep '/dev/([hsv]d[a-z]{1,2}|cciss/c[0-9]d[0-9]p|nvme[0-9]n[0-9]p)[0-9]{1,2}$'"`) registers the `ispartition` variable with a successful return code (0).

Later, the `prepare osd disk(s)` task is skipped because the condition

```
item.1.get("rc", 0) != 0
```

is not true.

We are using version `878dc47`, but it seems that these two parts are the same in master.

Do we need some pre-steps in order to use the roles with partitions?

**Comment by lhoss** [comment]
and following (solved and btw similar) issue suggests that devices based on partitions should be supported https://github.com/ceph/ceph-ansible/issues/636

**Comment by vincepii** [comment]
@leseb any ideas?

One thing that is changed is the

```
ignore_errors: true
```

that is gone in the activate OSD task (was there for sure ~1yr ago).

**Comment by leseb** [comment]
@vincepii hum I've never really used it myself. After looking at the code, you should have ended up to this task: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-osd/tasks/activate_osds.yml#L36-L47

Did the activation run?

**Comment by lhoss** [comment]
Hi @leseb,
actually we got the deployment done by doing 2 changes, that Im sure are not optimal for other use cases:
* disabling the check mentioned in the issue description:
> Later, the prepare osd disk(s) task is skipped because the condition
>```
>item.1.get("rc", 0) != 0
>```

* by re-adding in the task activation  (which I understand was removed in a PR, to 'fail early' on unwanted failures, which I'ld endorse as the right strategy)
```
ignore_errors: true
```

As this isn't a satisfactory solution, we did not want to create a PR.
IMO the right solution is to work on a proper detection of configured ceph partitions (when working with partitions instead of disks), as the current  <parted...|egrep '1....ceph'> check clearly fails when done a partition 'device' (as obviously a partition doesn't contain a partition table).

**Comment by zhsj** [comment]
Hi there,
you can try latest ceph-ansible to see whether it works well for partitions.

**Comment by vincepii** [comment]
We cannot test currently, but I am closing this issue.
Thanks for the work.
