### ISSUE TITLE
Ability to manage LVM journals

### ISSUE THREAD

**Issue by leseb** [ceph/ceph-ansible#9]
I believe there is a use case behind the lvm journals.
For instance you can do:

2 SSDs:
- tiny mdadm raid 1 setup for the system; let’s say /dev/sda1 and /dev/sdb1
- then you still have:
  - /dev/sda2
  - /dev/sdb2

They can both host journals, and you usually want to manage them with lvm, this is easier than managing partition.

**Comment by ivomarino** [comment]
I have a similar situation:

 - 1TB disk
   - /dev/sda1 (/dev/md0 == /boot)
   - /dev/sda2
   - /dev/sda3
   - /dev/sda4
   - /dev/sda5
   - /dev/sda6
   - /dev/sda7
   - /dev/sda8 (/dev/md1 == /)

 - 1TB disk
   - /dev/sdb1 (/dev/md0 == /boot)
   - /dev/sdb2
   - /dev/sdb3
   - /dev/sdb4
   - /dev/sdb5
   - /dev/sdb6
   - /dev/sdb7
   - /dev/sdb8 (/dev/md1 == /)

then I have one SSD for journals. What I would like to do is to use /dev/sda2 to /dev/sda7 (respectively /dev/sdbX) for OSDs, is this possible without erasing all data on /dev/sda due to ceph zap-disk (where also the OS resides)? If not what about eventually using LVM partitions build up on top of /dev/sda2 to /dev/sda7 for the OSDs? Thanks in advance for support.

**Comment by leseb** [comment]
AFAIR ceph-disk supports partition (so do we). So if /dev/sda2 to /dev/sda7 are partitions this should be good. The zap-disk is disabled by default so no worries.
If you give a partition though, the journal will end up being a file on the OSD data filesystem.

**Comment by ivomarino** [comment]
LVM disks are not supported or am I wrong? Tried to use a LVM disk as OSD and SSD disk as journal, zap disk on, SSD was formatted it seems but I got an error for LVM due to some overlapping partition table issues.

**Comment by leseb** [comment]
LVM disks are not supported by ceph-disk correct. I thought your issue was on the partition side.
I haven't seen any update for this, so you'll have to fallback to my workaround.

**Comment by ivomarino** [comment]
Your workaround means using partitions?

Strange thing when using parittions is that sda2 which is the first one always throws an error:
Warning! Secondary partition table overlaps the last partition by 33 blocks!

When I drop out /dev/sda2 /dev/sdb2 I get this error on sda3/sdb3 strangely, so the issue shifts up the OSD chain basically. Probably sda disk must have GPT and not MBR or similar.

**Comment by leseb** [comment]
Nop I meant this fix: https://github.com/ceph/ceph-ansible/issues/9#issuecomment-37127128

**Comment by ivomarino** [comment]
Allright, thanks. I think I'll stick with the partition solution, hopefully fixing "Warning! Secondary partition table overlaps the last partition by 33 blocks!" on /dev/sda2, etc.

**Comment by alsotoes** [comment]
I have to use LVM because the SCSI driver used by my PCIe flash card supports only 15 partitions, and the solution after create all using ceph-deploy osd create was this code in a for on my shell script.
My journal partitons are like:
/dev/mapper/vg_journal-lv_journal1p1
/dev/mapper/vg_journal-lv_journal2p1
etc...

And mi osd partitions are like:
/dev/sdb1
/dev/sdc1
etc...

```bash
#!/bin/sh

SERVER=$1
PARTITIONS="b c d e f g h i j k l m n o p q r s t u v w"
PIVOT="/mnt/osd-pivot"
AUX=1 

for i in $PARTITIONS; do
  	ceph-deploy --overwrite-conf osd --zap-disk create $SERVER:sd$i:/dev/mapper/vg_journal-lv_journal$AUX
  	ssh ${SERVER} mkdir -p ${PIVOT}
  	ssh ${SERVER} mount /dev/sd${i}1 ${PIVOT}

  	LVM_UUID=$(ssh ${SERVER} ls -l ${PIVOT}/journal | awk '{split($0,array," ")} END{print array[11]}' | sed  's|/dev/disk/by-partuuid/||g')
  	OSD_ID=$(ssh ${SERVER} cat ${PIVOT}/whoami)

  	ssh ${SERVER} umount ${PIVOT}
  	ssh ${SERVER} "mkdir -p /var/lib/ceph/osd/ceph-${OSD_ID}"
  	ssh ${SERVER} "rm -f /dev/disk/by-partuuid/${LVM_UUID}"
  	ssh ${SERVER} "cd /dev/disk/by-partuuid/ ; ln -s /dev/mapper/vg_journal-lv_journal${AUX}p1 ${LVM_UUID}"    
  	AUX=$(( $AUX + 1 ))
done
ssh ${SERVER} rm -rf ${PIVOT}

**Comment by leseb** [comment]
@alsotoes  Thanks for sharing, I'll see how we can incorporate this.

**Comment by socketpair** [comment]
http://tracker.ceph.com/issues/6042

**Comment by Asher256** [comment]
@leseb: about your comment:
```
udev doesn't create any links in /dev/disk/by-partuuid/ while using a partition on a LV
```

I confirm. That's why this issue happened https://github.com/ceph/ceph-ansible/issues/2209 . I solved it by setting a udev rule that creates a symlink '/dev/disk/by-partuuid/XXX' for each /dev/md* partitions (/dev/md* is a software RAID 1).  

Questions:
1. Do you have an idea why udev doesn't create '/dev/disk/by-partuuid/XXX' by default for '/dev/md*'?
2. According to your experience, what do you think about using a software RAID 1 for Ceph journals (in our configuration: 24HDD for OSDs + 2 fast PCIe SSD mdadm RAID 1 OSD journals)? 

(In my last benchmarks, the only drawback with software RAID 1 was 4x more latency for journal writing. The write speed in K/sec was the same)

**Comment by leseb** [comment]
@Asher256

1. I think this a udev/kernel decision.
2. I wouldn't use a RAID 1 for the journal as SSD in RAID1 tends to fail not simultaneously but the time between both is pretty low. So this a more dangerous than 2 separate SSD for journal.

**Comment by leseb** [comment]
I'm closing this as ceph-volume which is introduced in Luminous is going to replace ceph-disk and will play nice with lvm.

**Comment by Asher256** [comment]
@leseb: what would you do if you had a limit of 15 partitions per PCIe SSD? 
(I need at least 48 partitions per PCIe for the journal)

RAID-0 with mdadm?
LVM?
Other?

**Comment by leseb** [comment]
First, why so many partitions per SSD?

**Comment by Asher256** [comment]
This is my configuration: https://github.com/ceph/ceph-ansible/issues/2209 (I closed the issue, but the issue happened again today :( . I'm trying to find out why ceph-ansible fails with the error I described in the issue https://github.com/ceph/ceph-ansible/issues/2209).

I have 24 HDDs (OSDs) + 2 PCIe SSD for journals.

Because I use filestore=bluestore, ceph-ansible creates 2 partitions during the deployment. A total of 48 partitions.

**Comment by alfredodeza** [comment]
@Asher256 ceph-volume will allow you to have as many OSDs within a single device, because it can consume logical volumes. You would need to add your devices to a volume group, and then create as many data LVs from there.

If you have more questions, please use the mailing list

http://lists.ceph.com/listinfo.cgi/ceph-ansible-ceph.com
