### ISSUE TITLE
ceph-ansible should not disable swap

### ISSUE THREAD

**Issue by mbukatov** [ceph/ceph-ansible#919]
Right now, `ceph-common` role contains task which can disable swap and I see few issues with that (even though that the feature is disabled by default - which is good):

* having swap disabling task is out of scope of ceph-installer
* configuration doesn't survive reboot (it just executes command `swapoff -a`)

Reasoning
=========

Swap is usually configured by admin when the system is installed/deployed (since you need to create and enable swap partition), so when admin decides to deploy machines with swap, it doesn't make sense to override this decision in ceph-common role. When one needs to disable swap, it should be done on a deployment level, not in ceph-ansible. Also I'm not familiar with any ceph recommendations not to use swap.

Moreover it doesn't actually work (swap would be back after reboot).

So the question here is, should we just drop this feature or fix it?

Additional details
==================

I noticed that this has been introduced in this commit: https://github.com/ceph/ceph-ansible/commit/c246d8dc806f7b9a713b30010e436fac5a79ad71

And the default was fixed in: https://github.com/ceph/ceph-ansible/commit/4dad21c481de9f73f2f8308db0e00906b59f35b1

**Comment by leseb** [comment]
Thanks for bringing this on the table.
I don't fully agree when you said this is out of the scope, I think the installer should also provide guidance and optimization on the Ceph installation. This comes by applying Kernel tunables and several others like here: https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/tasks/misc/system_tuning.yml

However your reasoning makes sense as I believe it's not right to potentially override the admin configuration.
So I think we can remove this feature completely (since it won't survive a reboot) and other reasons listed above.

**Comment by mbukatov** [comment]
Ok, thanks for looking into this, I have created a pull request dropping the feature.

**Comment by mbukatov** [comment]
Since my pull request has been merged, I guess this could be closed now.
