### ISSUE TITLE
ceph-client failing because of undefined dmcrypt_journal_colocation and dmcrypt_dedicated_journal

### ISSUE THREAD

**Issue by jsaintrocc** [ceph/ceph-ansible#925]
I think this is related to PR #891.  Since the ceph-client role wouldn't include the ceph-osd defaults this check is failing for undefined dmcrypt variables.

```
TASK [ceph.ceph-common : verify only one osd scenario was chosen] **************
fatal: [pistore1-cc38-h01]: FAILED! => {"failed": true, "msg": "The conditional check '(journal_collocation and raw_multi_journal) or (journal_collocation and osd_directory) or (journal_collocation and bluestore) or (raw_multi_journal and osd_directory) or (raw_multi_journal and bluestore) or (osd_directory and bluestore) or (dmcrypt_journal_colocation and journal_collocation) or (dmcrypt_journal_colocation and raw_multi_journal) or (dmcrypt_journal_colocation and osd_directory) or (dmcrypt_journal_colocation and bluestore) or (dmcrypt_dedicated_journal and journal_collocation) or (dmcrypt_dedicated_journal and raw_multi_journal) or (dmcrypt_dedicated_journal and osd_directory) or (dmcrypt_dedicated_journal and bluestore)' failed. The error was: error while evaluating conditional ((journal_collocation and raw_multi_journal) or (journal_collocation and osd_directory) or (journal_collocation and bluestore) or (raw_multi_journal and osd_directory) or (raw_multi_journal and bluestore) or (osd_directory and bluestore) or (dmcrypt_journal_colocation and journal_collocation) or (dmcrypt_journal_colocation and raw_multi_journal) or (dmcrypt_journal_colocation and osd_directory) or (dmcrypt_journal_colocation and bluestore) or (dmcrypt_dedicated_journal and journal_collocation) or (dmcrypt_dedicated_journal and raw_multi_journal) or (dmcrypt_dedicated_journal and osd_directory) or (dmcrypt_dedicated_journal and bluestore)): 'dmcrypt_journal_colocation' is undefined\n\nThe error appears to have been in '/Users/jsaint201/ceph-ansible-master/roles/ceph-common/tasks/checks/check_mandatory_vars.yml': line 86, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: verify only one osd scenario was chosen\n  ^ here\n"}
    to retry, use: --limit @site.retry
```

**Comment by leseb** [comment]
@jsaintrocc do you mind sending a PR for this?

**Comment by jsaintrocc** [comment]
Sure thing.

**Comment by leseb** [comment]
Thanks!

**Comment by jsaintro** [comment]
So I figured out this was caused by me adding the Client role to the 1st OSD.  I did that so that pools would get created automatically.  So 2 questions:

What do you think about me moving the pool creation code somewhere else (Maybe the OSD role)?  Initially I though the mon role would be better but obviously you're depended on the OSD's being there before you can create the pools.  

Is there ever a case where an OSD should also be allowed to have the client role?  If not I could write a check to fail if that's the case.

**Comment by jsaintrocc** [comment]
^^^ Sorry was logged in with my personal account ;-)

**Comment by leseb** [comment]
Hey @jsaintrocc, that's fine creating pools without OSDs, PG won't be allocated but will be as soon as OSDs show up.
The best way to fix this issue is to move all the corresponding checks to the appropriate roles and stop putting everything in ceph-common, see https://github.com/ceph/ceph-ansible/blob/master/roles/ceph-common/defaults/main.yml#L348-L370 as a reference.
This means the pool creation code can remain in ceph-client.
Usually I don't think OSDs should be treated as clients, but for whatever purpose it might be needed. I won't recommend that but in some obscur benchmarking circonstances it can be useful.

**Comment by jsaintrocc** [comment]
Hey @leseb, both mon and client roles have tasks to create pools but the client tasks are more flexible.  I was thinking about moving the client pool creation tasks to the mon role (replacing it's pool creation tasks).  That way we remove the redundancy and also provide a more flexible way to create pools (without needing to add a client).  What do you think of that approach?

**Comment by leseb** [comment]
It is more flexible indeed and the fact that we don't need to deploy a client saves us unnecessary ansible tasks (if we colocate ceph-mon and ceph-client role on the same machine we will play ceph-common twice).
Although, do not drop the ceph-client role, we still need it. (iSCSI RBD is on its way to this repo ;))

**Comment by leseb** [comment]
Fixed, these variables are part of roles/ceph-common/defaults/main.yml
